### PR TITLE
⚠️ Go module fullfillment for v2+

### PR DESCRIPTION
**Pull request by Adirio**
Targets #1791 for future versions

Fixes: #1562

It is not technically a breaking change but requires action from third-parties.

### CODE REVIEW

**Review by camilamacedo86 — COMMENTED** [review]
Since the next release will be 3.0.0 and we cannot so longer push a patch release from master anyway then, IMO all here should be `v3`instead of `v2`. Otherwise, I am ok with the changes made. 

c/c @pwittrock @estroz @DirectXMan12 wdyt?

**Comment by Adirio** [comment]
Are we 100% certain next kubebuilder version is going to be 3.0.0? Remember that I'm not talking about neither the kubebuilder base plugins nor the project configuration file version.

**Review by estroz — APPROVED** [review]
/approve

**Comment by Adirio** [comment]
I think that with #1798 tracking the change to `v3`, this can be merged. It requires `lgtm`.

**Pull request merged**
