### PR TITLE
✨  : make go/v4 to be default Kubebuilder CLI scaffold

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Description

Make go/v4 layout the default layout of kubebuilder CLI
Now, new projects init without inform plugin will be created using go/v4 by default.

NOTE: It does not break the behaviour for those with a project scaffold with go/v3. It only makes the default scaffold of the the CLI to be go/v4 

## Motivation

https://github.com/kubernetes-sigs/kubebuilder/issues/3117
https://github.com/kubernetes-sigs/kubebuilder/discussions/3217

### CODE REVIEW

**Review by Kavinjsir — APPROVED** [review]
Generally looks good! Some nits:

1. Some comments under `test/testdata/generate.sh` can be updated with `v4`:
    - https://github.com/kubernetes-sigs/kubebuilder/blob/v3.9.1/test/testdata/generate.sh#L132
    - https://github.com/kubernetes-sigs/kubebuilder/blob/v3.9.1/test/testdata/generate.sh#L140

2. We may update the usage of `go/v3` in e2e test for deploy-image:
    - https://github.com/kubernetes-sigs/kubebuilder/blob/v3.9.1/test/e2e/deployimage/plugin_cluster_test.go#L83
    - https://github.com/kubernetes-sigs/kubebuilder/blob/v3.9.1/test/e2e/deployimage/plugin_cluster_test.go#L120

**Review by everettraven — APPROVED** [review]
Changes look good to me! I noticed @Kavinjsir had some nits that make sense to me so I will hold on the LGTM for now so it doesn't automerge and they can be discussed.

**Comment by camilamacedo86** [comment]
Hi @Kavinjsir,

The idea here is we only make the go/v4 the default scaffolds. Then, in other follows ups we can change our testdata (which does not affect and user), reduce the tests and etc. 

So, I hope that it make sense and we can agree in improve the maintainability as I understand that you request here: https://github.com/kubernetes-sigs/kubebuilder/pull/3278#pullrequestreview-1336232639 via follow ups.   

Example: https://github.com/kubernetes-sigs/kubebuilder/pull/3275

WDYT? @Kavinjsir @everettraven

**Comment by Kavinjsir** [comment]
> 

Sounds good to me! 👍🏼

**Comment by camilamacedo86** [comment]
/hold cancel

@everettraven @varshaprasad96 @Kavinjsir could one of you just LGTM this one please?

**Pull request merged**
