### PR TITLE
:seedling: update refs to go-test make target

### PR DESCRIPTION
**Pull request by michelleN**
* Should be make test-unit now as of
https://github.com/kubernetes-sigs/kubebuilder/commit/8c0816155d88c475cd6b703267b0e7840776a0a2#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L90

Signed-off-by: Michelle Noorali <minooral@microsoft.com>

### CODE REVIEW

**Review by Adirio — DISMISSED** [review]
`:ghost:` is not understood, use `:seedling:`.

There are more changes to do to this section but you are right with this change.

/kind documentation

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Comment by camilamacedo86** [comment]
HI @Adirio, 

I this case we can update to help the contributor. So, that is done 👍

**Comment by michelleN** [comment]
Thanks @camilamacedo86 and @Adirio - please let me know if I need to anything else!

**Pull request merged**
