### PR TITLE
doc: add info to check changes in the docs

### PR DESCRIPTION
**Pull request by camilamacedo86**
add note in contributing.md about where to find the netlify preview

### CODE REVIEW

**Comment by DirectXMan12** [comment]
There's actually easier instructions -- just click the "details" link next to the `netlify/kubebuilder/deploy-preview` github check.  We probably want to note that instead

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12, 

I did not get. let's imagine as a person that who just started to contribute with and would like to do a good first issue. How/Where this person is able to find this info?

**Comment by DirectXMan12** [comment]
Oh yeah, we should totally document that -- I'm just saying that instead of telling people "type in this URL" we tell people "click the link under checks" :-)

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12,  
Done 👍 Tks for the input.

**Comment by DirectXMan12** [comment]
edited description -- in the future, please add PR descriptions.

/lgtm
/approve

**Pull request merged**
