### PR TITLE
Update  Copyright year

### PR DESCRIPTION
**Pull request by Sajiyah-Salat**
The new year has already begun. I have update all the file with copyright year.

### CODE REVIEW

**Review by camilamacedo86 — CHANGES_REQUESTED** [review]
This one we need to do a fully updated.
That would mean run the generate scripts with the latest changes, then came back the code, then run make to ensure that is all ok, 

See; https://github.com/kubernetes-sigs/kubebuilder/issues/2510 for a better understanding

**Comment by Sajiyah-Salat** [comment]
Thank you @camilamacedo86 even if this is not a good first issue. I would like to understand more about it and will try to change that. the pr link you provided is not enough to understand the whole matter. let me know if there are other good resources available or we can connect in your free time to discuss the issue.  Thank you.

**Comment by Kavinjsir** [comment]
@camilamacedo86 I agree that we may cover this topic under https://github.com/kubernetes-sigs/kubebuilder/issues/2510
(If I'm understanding correctly)

Manual update of the copyright year and have an additional commit in the version control history can be redundancy.

**Comment by Sajiyah-Salat** [comment]
After going through all comments I think I understand few things and whats going on and what needs to change. I ran make generate command after changing the copyright year. and the deepcopy file changes. The thing is if we change anything in code and run make generate. machine generate its own code. Right? In this case we can just add one command in contributing.md telling contributors to run make generate before pushing your code. 
Also my generate code file deecopy is not seen in changed files while my commit is visible why?

**Comment by Sajiyah-Salat** [comment]
Can I work on website and the code blocks given in cronjob tutorial. I will add some features and remove some bugs which I have gone through following the tutorial. @camilamacedo86 let me know your thoughts regarding that.

**Comment by Kavinjsir** [comment]
> After going through all comments I think I understand few things and whats going on and what needs to change. I ran make generate command after changing the copyright year. and the deepcopy file changes. The thing is if we change anything in code and run make generate. machine generate its own code. Right? In this case we can just add one command in contributing.md telling contributors to run make generate before pushing your code. Also my generate code file deecopy is not seen in changed files while my commit is visible why?

@Sajiyah-Salat 
1. If you are not clear about what happens when executing `make generate`, you may check `Makefile` and walk through the corresponding files such as `test/testdata/generate.sh`.
2. We have stated the usage of `make generate` in [CONTRIBUTING.md](https://github.com/kubernetes-sigs/kubebuilder/blob/v3.9.0/CONTRIBUTING.md#what-to-do-before-submitting-a-pull-request). It will be very appreciated if you may read through the file before uploading a PR.

**Comment by camilamacedo86** [comment]
Hi @Sajiyah-Salat,

> Can I work on website and the code blocks given in cronjob tutorial. I will add some features and remove some bugs which I have gone through following the tutorial. @camilamacedo86 let me know your thoughts regarding that.

Yes, you are free to contribute with all and more than welcome.

However, this one is about update the [Copyright year](https://github.com/kubernetes-sigs/kubebuilder/pull/3173#top) and I think we conveyed that the right way to update the samples in the docs is by re-generating them with the scripts as described in https://github.com/kubernetes-sigs/kubebuilder/issues/2510.

That is a manually process until we be able to provide a better solutions which is the end goal of the task: https://github.com/kubernetes-sigs/kubebuilder/issues/2510

So, I think we can close this one. WDYT?

c/c @Kavinjsir

**Comment by Kavinjsir** [comment]
@camilamacedo86 I agree. We can explore this while go overing https://github.com/kubernetes-sigs/kubebuilder/issues/2510

**Comment by camilamacedo86** [comment]
Closing this one.

**Pull request closed without merging**
