### PR TITLE
🐛 update config-gen to match v3 expectations

### PR DESCRIPTION
**Pull request by pwittrock**
- Migrate to use the latest flag names
- Use the latest controller-tools version
- Only generate webhooks if enabled

### CODE REVIEW

**Comment by christopherhein** [comment]
/lgtm

thank you @pwittrock for doing this, I'm excited to see `config-gen` in use. This looks like it will help a lot with the next steps for rolling ComponentConfig support out.

**Comment by Birdrock** [comment]
There are still some references to `--enable-leader-election` that are not part of v2 scaffolds or migration guides. It might be worth checking the references to ensure they are still relevant.

* docs/book/src/component-config-tutorial/api-changes.md
* pkg/cli/alpha/config-gen/templates/resources/controller-manager.template.yaml
* pkg/cli/alpha/config-gen/testdata/disableauthproxy/expected.yaml

Two of these files are in alpha, so this may be an incorrect call-out on my part.

**Comment by pwittrock** [comment]
@Birdrock 

> There are still some references to --enable-leader-election that are not part of v2 scaffolds or migration guides. It might be worth checking the references to ensure they are still relevant.

Updated the config-gen ones

**Comment by christopherhein** [comment]
/lgtm

🎉

**Comment by pwittrock** [comment]
@Adirio @estroz @camilamacedo86 any concerns with the `go.sum` changes?

**Pull request merged**
