### PR TITLE
minor typo fix in kind string format validation

### PR DESCRIPTION
**Pull request by Azadehkhojandi**
kinds expected to be Pascal case

### CODE REVIEW

**Comment by Azadehkhojandi** [comment]
I've signed CLA

**Comment by mengqiy** [comment]
Please run `generated_golden.sh` to re-gen test projects.

**Comment by DirectXMan12** [comment]
This prob needs to be fixed in v2 as well, right?

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12,
 
It is in the resource.go so shows that it used for both currently. In this way, it is quite small too and for me, it shows /lgtm 👍

**Pull request merged**
