### PR TITLE
rename config to deploy for v2

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description of the change:**
Rename the path config for deploy in order to make easier and intuitive.

**Motivation for the change:**
https://github.com/kubernetes-sigs/kubebuilder/issues/1051

### CODE REVIEW

**Comment by camilamacedo86** [comment]
Hi @folks,

If you accept it, has just one thing that I need help here. The role.yaml was not created in the dir deploy/rbac/role.yaml. Where it is has been defined?

**Comment by camilamacedo86** [comment]
HI, 

I need a help here to understand why the role.yaml has been not created in the deploy ir after the change. 

```
 $ make deploy IMG=cmacedo/testdeploy:test
/Users/camilamacedo/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=deploy/crd/bases
cd deploy/manager && kustomize edit set image controller=cmacedo/testdeploy:test
kustomize build deploy/default | kubectl apply -f -
Error: accumulating resources: recursed accumulation of path '../rbac': accumulating resources: accumulating resources from 'role.yaml': evalsymlink failure on '/Users/camilamacedo/go/src/sigs.k8s.io/test/deploy/rbac/role.yaml' : lstat /Users/camilamacedo/go/src/sigs.k8s.io/test/deploy/rbac/role.yaml: no such file or directory
error: no objects passed to apply
make: *** [deploy] Error 1

$ cd deploy/
$ ls
certmanager	crd		default		manager		rbac		samples		webhook
$ cd rbac/
$ ls
auth_proxy_role.yaml			auth_proxy_service.yaml			leader_election_role.yaml		role_binding.yaml
auth_proxy_role_binding.yaml		kustomization.yaml			leader_election_role_binding.yaml
```

**Comment by DirectXMan12** [comment]
When you add a motivation block, please try to have normal text in addition to an issue reference -- it helps when reading the commit log.

**Comment by DirectXMan12** [comment]
We can't do this in v2 w/o breaking compat.  This'd have to be v3.

**Comment by camilamacedo86** [comment]
So, for any new version, the code will be replicatedin the v-N dir and v-test and v-testdata?

**Comment by DirectXMan12** [comment]
We'd have to have a v3 scaffolding version.  Let's hold off on that for the moment, and add it to the list of things we want to tackle for that.

**Comment by camilamacedo86** [comment]
I understand that the changes of https://github.com/kubernetes-sigs/kubebuilder/issues/1025 would also be fit in the V3.

**Comment by DirectXMan12** [comment]
yeah, we can create a milestone.  Let me do that now

**Comment by DirectXMan12** [comment]
I've added this to the scaffolding-v3 milestone as an example

**Comment by camilamacedo86** [comment]
I am closing the PR @DirectXMan12 because we need to create the V3 structure. Could you please add the issue #1051 in the scaffolding-v3?

**Pull request closed without merging**
