### PR TITLE
🌱 : fix traling spaces in the docs and add check as automate fix to the make generate

### PR DESCRIPTION
**Pull request by camilamacedo86**
Just fix and check in the CI for trailing spaces

### CODE REVIEW

**Comment by camilamacedo86** [comment]
@bzub @mateusoliveira43

See now we can solve it across the whole project when we run make generate
Also, now we are checking of the spaces so we will not get merged stuff with trailing spaces.

**Review by Kavinjsir — APPROVED** [review]
Looks good to me!

**Comment by camilamacedo86** [comment]
Hi @Kavinjsir 

Can you please either create a comment `/lgtm` so that we can get this one merged ?
thank you ❤️

**Pull request merged**
