### PR TITLE
:book: add details rbac doc in tutorial

### LINKED ISSUE #3105: About the RABC
### What broke? What's expected?

when I  run as the Quickstart, I met a problem with the  rabc. why it  does't add job.batch automatic ? All the code I copy from the  https://book.kubebuilder.io/cronjob-tutorial/cronjob-tutorial.html . Kindly anybody help? 

image

 manager: Container log
E1130 09:49:18.202269       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.Job: failed to list *v1.Job: jobs.batch is forbidden: User "system:serviceaccount:test-operator-system:test-operator-controller-manager" cannot list resource "jobs" in API group "batch" in the namespace "test-operator-system"
W1130 09:49:25.068788       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list *v1.Job: jobs.batch is forbidden: User "system:serviceaccount:test-operator-system:test-operator-controller-manager" cannot list resource "jobs" in API group "batch" in the namespace "test-operator-system"
E1130 09:49:25.068815       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.Job: failed to list *v1.Job: jobs.batch is forbidden: User "system:serviceaccount:test-operator-system:test-operator-controller-manager" cannot list resource "jobs" in API group "batch" in the namespace "test-operator-system"
W1130 09:49:38.234719       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list *v1.Job: jobs.batch is forbidden: User "system:serviceaccount:test-operator-system:test-operator-controller-manager" cannot list resource "jobs" in API group "batch" in the namespace "test-operator-system"
E1130 09:49:38.234754       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.Job: failed to list *v1.Job: jobs.batch is forbidden: User "system:serviceaccount:test-operator-system:test-operator-controller-manager" cannot list resource "jobs" in API group "batch" in the namespace "test-operator-system"

### Reproducing this issue

_No response_

### KubeBuilder (CLI) Version

3.7

### PROJECT version

v1

### Plugin versions

_No response_

### Other versions

_No response_

### Extra Labels

/kind documentation

### PR DESCRIPTION
**Pull request by qingwave**
Add details rbac doc in tutorial.

Fixes #3105

### CODE REVIEW

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

/ok-to-test

**Comment by qingwave** [comment]
test failed due to setup-envtest issue, see https://github.com/kubernetes-sigs/controller-runtime/issues/2086

**Comment by camilamacedo86** [comment]
Could you please ensure that you have it rebased with master branch?

/approved cancel

**Comment by qingwave** [comment]
> Could you please ensure that you have it rebased with master branch?
> 
> /approved cancel

Sure, I base on the latest master

**Pull request merged**
