### PR TITLE
🐛 Improve scaffolding to filter existing multiline code fragments

### LINKED ISSUE #2326: scheme marker in suite_test.go generates duplicate code
### Expected

The `//+kubebuilder:scaffold:scheme` marker that kubebuilder includes in the scaffolded `controllers/suite_test.go` file should only generate new code when there is a new scheme to add. This is how the marker behaves in main.go.

### Actual

Every time you run `kubebuilder create api` to add a new CRD to an existing API group, the marker adds the same code block, and you end up with a lot of unnecessary duplicate code, like:

```go
err = myappv1.AddToScheme(scheme.Scheme)
Expect(err).NotTo(HaveOccurred())

err = myappv1.AddToScheme(scheme.Scheme)
Expect(err).NotTo(HaveOccurred())

//+kubebuilder:scaffold:scheme
```

### Reproducing this issue

```shell
mkdir kubebuilder-test
cd kubebuilder-test
go mod init myapp.example.com
kubebuilder init --domain example.com
kubebuilder create api --version=v1 --resource --controller --group=myapp --kind Foo
kubebuilder create api --version=v1 --resource --controller --group=myapp --kind Bar
cat controllers/suite_test.go
```

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.1.0", KubernetesVendor:"unknown", GitCommit:"92e0349ca7334a0a8e5e499da4fb077eb524e94a", BuildDate:"2021-05-29T05:57:53+01:00", GoOs:"darwin", GoArch:"amd64"}

### PROJECT version

version: "3"

### Plugin versions

```yaml
layout:
- go.kubebuilder.io/v3
```

### Other versions

_No response_

### Extra Labels

_No response_

### PR DESCRIPTION
**Pull request by armsnyder**
Signed-off-by: Adam Snyder <armsnyder@gmail.com>

Scaffolding can only detect existing generated code if the code fragments are single-line. As a result, multi-line scaffolding can be inserted into code more than once. This fix improves the scaffolding to detect multi-line code fragments and not inject them.

Fixes #2326

### CODE REVIEW

**Review by camilamacedo86 — CHANGES_REQUESTED** [review]
.

**Review by camilamacedo86 — DISMISSED** [review]
Thank you for your contribution. 🥇 
Yes, you are right that was duplicated.

**Comment by armsnyder** [comment]
@camilamacedo86 Thanks, I rebased and the API check passes. Just to note, when I ran `make generate` it added an unrelated line which should fix the master branch failing.

**Review by camilamacedo86 — APPROVED** [review]
/approved

**Pull request merged**
