### PR TITLE
Publish Kubernetes 1.19 tools

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

/assign @mengqiy @DirectXMan12

### CODE REVIEW

**Comment by vincepri** [comment]
@DirectXMan12 I think we have to merge these manually until we get the owner file setup, or apply the `approved` label by hand if you have permissions

**Comment by DirectXMan12** [comment]
I just manually pushed boilerplate to that branch, let's try the command again

/approve

**Comment by DirectXMan12** [comment]
(also added some instructions so future generations have *any* idea what's going on ;-) )

**Pull request merged**
