### PR TITLE
📖 fix typo in the design docs to scaffold projects

### PR DESCRIPTION
**Pull request by Sajiyah-Salat**
Hello, I was going through the proposal and its well written but I found this typo and tried to fix this. Aince this is just a two words change. I dont  feel like opening a issue for that. if its mandatory I will do that. Thank you.

### CODE REVIEW

**Review by jmrodri — APPROVED** [review]
/lgtm

**Comment by Sajiyah-Salat** [comment]
Okay, I will do this shortly.

**Pull request merged**
