### PR TITLE
✨ Build the command and use it to report user errors

### PR DESCRIPTION
**Pull request by Adirio**
Improve error reporting by printing the command usage
Fixes: #1913
Fixes: #1914
Fixes: #1915

### CODE REVIEW

**Comment by Adirio** [comment]
@estroz I removed the `doHelp` field again that you restored in #1900 but I think this PR behavior is correct now. Basically the `"base"` flagset was printing its usage message in case we had the `--help` or `-h` flags as that is hardcoded before the whitelist filter, so by adding a dummy `--help` and `-h` flag to this base FlagSet we prevent this behavior and we delegate into the cobra command to print its usage.

**Review by camilamacedo86 — APPROVED** [review]
/approve 

Great work. it shows terrific for me 👍

**Comment by estroz** [comment]
@Adirio this behavior does look a lot better.

/lgtm

**Pull request merged**
