### PR TITLE
:seedling: remove alpha subcommand since it is no longer used

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description**
- remove alpha subcommand since it is no longer used

**Motivation** 

It is a dead/unused code. Also, after the [plugin implementation](https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/extensible-cli-and-scaffolding-plugins-phase-1.md) the idea is that the Kubebuilder commands are extensible. In this way, any new feature and subcommand would be a plugin which makes this feature be useless for future possible cases as well.

### CODE REVIEW

**Review by Adirio — APPROVED** [review]

**Comment by Adirio** [comment]
LGTM, as soon as it passes the tests I'l set the `lgtm` label

**Comment by camilamacedo86** [comment]
I will force the merged because of `coverage/coveralls — Coverage decreased (-0.2%) to 71.774%`

**Pull request merged**
