### PR TITLE
Unification of receiver names

### PR DESCRIPTION
**Pull request by Adirio**
Linter is reporting different receiver names (i.e., methods of same struct with different receiver names) as if they were generic. Additionally most of the files use generic receivers such as `a`. Tiis PR changes all receiver names for implementations fo the `File` interface to `f` as a mnemonic of `file`.

Closes: #1182

/kind cleanup

### CODE REVIEW

**Comment by Adirio** [comment]
Note to reviewers: do not get scared with the number of files modified. They are just pointer name replacements to use `f` for all of them instead of `a`, `c`, `g`, ...

**Comment by camilamacedo86** [comment]
Hi @Adirio, 

It shows good, however, see that is not passing in the CI. So, something brokes.
Also, I'd recommend you add here in the first comment the error/warning from the linter used to get it which shows that is your motivation of   `Umbrella issue: #1176`

**Comment by Adirio** [comment]
Can someone re-trigger Travis? It gave an error trying to find a file that hasn't been touched and is in the expected path.

**Comment by camilamacedo86** [comment]
HI @Adirio, 

> Can someone re-trigger Travis? It gave an error trying to find a file that hasn't been touched and is in the expected path. 

If you close and re-open the PR it will be re-trigged.

**Comment by Adirio** [comment]
Hi @camilamacedo86,
 
> It shows good, however, see that is not passing in the CI. Shows that it is missing a rebase with the master to pass in the CI. Also, I'd recommend you add here in the first comment the error/warning from the linter used to get it which shows that is your motivation of `Umbrella issue: #1176`

The rebase was done and the CI is passing correctly. Description was also updated. Do you have any other review or is this PR ready to merge?

**Comment by Adirio** [comment]
Rebased (no changes)

**Comment by Adirio** [comment]
There were two additional files that I were added after this PR so included them.

**Comment by DirectXMan12** [comment]
uuhhh, what's the purpose of changing all these to the same letter?  That's effectively a generic receiver name (it's the same as using `this` or `self`).  Having specific letters that abbrieviate the actual receiver type is nice because it helps you remember what type you're in, which variable is the receiver, etc.

/hold

**Comment by Adirio** [comment]
> uuhhh, what's the purpose of changing all these to the same letter? That's effectively a generic receiver name (it's the same as using `this` or `self`). Having specific letters that abbrieviate the actual receiver type is nice because it helps you remember what type you're in, which variable is the receiver, etc.

The problem is that right now they are all using different patterns:

<details><summary>List of the first 15</summary>
- `r`
  - `AuthProxyRole`
  - `AuthProxyRoleBinding`
  - `AuthProxyRoleService`
- `c`
  - `Boilerplate`
  - `GitIgnore`
  - `Kustomize`
  - `KustomizeManager`
  - `KustomizeRBAC`
  - `Makefile`
  - `Project`
- `g`
  - `GopkgToml`
- `a`
  - `AddController`
  - `Controller`
  - `SuiteTest`
  - `Test`

Can add the rest if needed.
</details>

You could debate that `GopkgTml` and `g` makes sense, or maybe that `r` comes from `Role` for those three files, but what about the rest? There are also some examples in `v2` that have different receivers for the `GetInput` and the `Update` methods, which is being hinted by some linters.

**Comment by Adirio** [comment]
Closing and reopening to retrigger Travis as Mac failed without description: https://travis-ci.org/kubernetes-sigs/kubebuilder/builds/622593619

**Comment by Adirio** [comment]
@DirectXMan12 Could you make a final decission in respect to this topic?

_Note: the reason behind requesting for a final decission is to take it into account for the scaffold enhancement that I am doing under #1218._

In case `f` for file sounds too generic for the 73 `File` implementations that there currently are in kubebuilder, should the other generics (such as `a` for most of the Files) also be changed to a single letter that represents the type? I like the `f` approach because it remembers that it is a `File` implementation while the directory, file name and type name already give a hint about what it is for.

If the final decission is to move away from `f` this PR can be closed and I will take into account in the scaffolding enhancement, if not it can be merged and I will keep using `f` in following PRs.

**Comment by DirectXMan12** [comment]
> In case f for file sounds too generic for the 73 File

OOOOOOHHHHH.  That's the mnemonic.  Sorry, that was lost during code review ;-).  `f` is fine for file.  That makes a whole lot more sense now :-)

/lgtm
/approve

**Comment by DirectXMan12** [comment]
(just needs a rebase)

**Comment by Adirio** [comment]
> > In case f for file sounds too generic for the 73 File
> 
> OOOOOOHHHHH. That's the mnemonic. Sorry, that was lost during code review ;-). `f` is fine for file. That makes a whole lot more sense now :-)

I thought I mentioned it somewhere. You know, when you change it in 73 files, it is easy to take gfor granted that the mnemonic is obvious. Added it to the PR description for future reference.

> (just needs a rebase)

Done

**Comment by Adirio** [comment]
Travis error seems to be related to #1016 being recently merged.

**Comment by camilamacedo86** [comment]
HI @Adirio, 

The error shows occur because the files are not updated. I'd recommend you do the following steps. I think it will solve.

1. Rebase with the master
2. Run `make generate` (it will do all tricks to run the golden script properly)

**Comment by Adirio** [comment]
This already was rebased, and it doesn't change anything in the testdata folder. The problem seems to be introduced by an old PR that was merged yesterday.

**Comment by Adirio** [comment]
A fix to the Travis error has been provided in #1288, it shouldn't need a rebase afterwards.

**Comment by Adirio** [comment]
Rebased to apply the fix to Travis. This should only need a `lgtm` label.

@camilamacedo86 @DirectXMan12

**Comment by Adirio** [comment]
I will resolve the conflicts tomorrow

/hold cancel

**Comment by Adirio** [comment]
@mengqiy Rebased and ready, only requires LGTM label

**Comment by Adirio** [comment]
Travis error seems unrelated, please take a look at #1303.

**Comment by Adirio** [comment]
This PR has been approved and every test passes now. Can someone add again the lgtm label as it was removed in a rebase?

**Comment by Adirio** [comment]
@camilamacedo86

**Pull request merged**
