### PR TITLE
Typo: CronJobSpec StartingDeadlineSeconds should be int32

### PR DESCRIPTION
**Pull request by daneharrigan**
Offering a fix to the issue I opened #921 921

### CODE REVIEW

**Comment by daneharrigan** [comment]
The `project/pkg/controller/namespace` test may be flaky. I'll run the tests a few more times locally and create an issue if that's the case.

**Comment by daneharrigan** [comment]
The `project/pkg/controller/namespace` package passes consistently on my local machine. I think the failure I experienced before was due to a bad default kubectl context. Please ignore my original concern about the test being flaky

**Comment by DirectXMan12** [comment]
I've commented on the related issue -- namely, I can't find the "must be int32" line anymore in the k8s api conventions, so I think we can just fix this message in CT and the book instead.

**Pull request closed without merging**
