### PR TITLE
Include the dep command as an example

### PR DESCRIPTION
**Pull request by coderanger**
For dep newbies like me :)

### CODE REVIEW

**Comment by DirectXMan12** [comment]
it's generally one or the other -- you shouldn't need to do both in the normal case.

**Comment by pwittrock** [comment]
Can we add this as a separate thing instead of telling folks to do it by default.  e.g. `If you run into errors about conflicts, run ...`

**Comment by mengqiy** [comment]
> Can we add this as a separate thing instead of telling folks to do it by default. e.g. If you run into errors about conflicts, run ...

@coderanger Can you please update the PR?

**Comment by DirectXMan12** [comment]
No longer using dep, closing

**Pull request closed without merging**
