### PR TITLE
📖: Update go version in docs to v1.20

### PR DESCRIPTION
**Pull request by yyy1000**
### Description
Since the master branch has updated the go version to v1.20, we can also update that in the docs.

### CODE REVIEW

**Comment by yyy1000** [comment]
Oh, the pipeline fails. I think it's not the fault in the PR, but the master branch. Hopefully, this PR #3391 will update the testdata and the pipeline could pass.

**Review by camilamacedo86 — COMMENTED** [review]
Can you please rebase with the master?

/ok-to-test

**Comment by yyy1000** [comment]
Rebase done.

**Review by camilamacedo86 — APPROVED** [review]
/lgtm
/approved 
/ok-to-test

**Pull request merged**
