### PR TITLE
:running: Extract Resource from the v1 scaffolding package

### LINKED ISSUE #1144: Extract Resource from the v1 Scaffolding package
The `Resource` type is being used by both scaffolding versions, but it is placed inside v1, which is missleading. Furthermore, v1 scaffolding is being deprecated (#1136, #1137).

Shouldn't this package be extracted to the root scaffolding package?

/kind feature

### PR DESCRIPTION
**Pull request by Adirio**
# Description
Move `Resource` and associated tests one package above.

# Motivation
Extract common functionality out of the `v1` specific dir, what should help deprecating v1 (#1136).

Fixes #1144

### CODE REVIEW

**Comment by mengqiy** [comment]
/lgtm
/approve
Thanks for cleanup things

**Comment by Adirio** [comment]
Travis is [failing because of a checksum of k8s.io/apimachinery](https://travis-ci.org/kubernetes-sigs/kubebuilder/jobs/609442705#L1626-L1649). I didn't make any change related to that. Any clue why this may be happening?

**Comment by Adirio** [comment]
I rebased and force-pushed to see if #1135 solves the Travis issue. Could you add /lgtm label again @mengqiy? Sorry for the inconveniences.

**Pull request merged**
