### PR TITLE
📖 Docs update quick-start.md use "kubectl -k apply"

### LINKED ISSUE #3499: quick start error deploying sample CR
### What broke? What's expected?

Following the quickstart https://book.kubebuilder.io/quick-start.html#install-instances-of-custom-resources

The command produce error
```
kubectl apply -f config/samples/
```
The error
```
guestbook.webapp.my.domain/guestbook-sample created
error: error validating "config/samples/kustomization.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
```

Workaround use `-k`
```
kubectl apply -k config/samples/
```

### Reproducing this issue

_No response_

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.11.1", KubernetesVendor:"1.27.1", GitCommit:"1dc8ed95f7cc55fef3151f749d3d541bec3423c9", BuildDate:"2023-07-03T13:10:56Z", GoOs:"linux", GoArch:"arm64"}

### PROJECT version

_No response_

### Plugin versions

_No response_

### Other versions

_No response_

### Extra Labels

/kind documentation

### PR DESCRIPTION
**Pull request by csantanapr**
Fixes #3499

### CODE REVIEW

**Review by Kavinjsir — APPROVED** [review]
LGTM 👍🏼

**Review by camilamacedo86 — CHANGES_REQUESTED** [review]
I think we should not merge this one,
See your error: error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false

You probably did not executed `make manifests` to properly generate the manifests.

**Comment by csantanapr** [comment]
Hi @camilamacedo86 


I ran `make manifests` 

The problem is that with using `-f` in kubectl apply it will process the two files as kubernetes manifest files, the `kustomization.yaml` is not a kubernets manifest is a kustomize manifest and you need to use `kubectl -k` not `kubectl -f`

you if you want to use `-f` then you need to specify the file `kubectl -f config/samples/webapp_v1_guestbook.yaml` 
```
ls -l config/samples/ 
total 8
-rw------- 1 vscode vscode 124 Jul 21 17:40 kustomization.yaml
-rw------- 1 vscode vscode 361 Jul 21 17:40 webapp_v1_guestbook.yaml
```

This PR should be merge to use be able to process the directory that has a kustomize file

**Review by camilamacedo86 — APPROVED** [review]
I see the error is with `error: error validating "config/samples/kustomization.yaml":`


/lgtm

**Pull request merged**
