### PR TITLE
🐛 For go/v3, ensure that the plugin can only be used with its go supported version >= 1.17 and < 1.18

### PR DESCRIPTION
**Pull request by Ankit152**
Hey @camilamacedo86 🙂 

Here is the new PR. Hope this time it works absolutely fine.

### CODE REVIEW

**Comment by camilamacedo86** [comment]
The prints with the local tests to show that it works are in; https://github.com/kubernetes-sigs/kubebuilder/pull/2546#issuecomment-1070983260

So, 

/lgtm

**Review by camilamacedo86 — APPROVED** [review]

**Comment by Ankit152** [comment]
@camilamacedo86 Thank you for merging the pull request 🙂

**Pull request merged**
