### PR TITLE
✨ Add machinery utility functions

### PR DESCRIPTION
**Pull request by Adirio**
This PR adds machinery utility function to insert, replace or prefix/unprefix parts of the code.

Similar functions were being provided in the `test` package which should probably not export anything API-wise.

TODO:
- [ ] Unit tests

### CODE REVIEW

**Comment by Adirio** [comment]
TODO: tests

/test all

**Comment by Adirio** [comment]
@camilamacedo86 @estroz I would like to get some feedback on the conceptual idea and functions signature before implementing the tests.

**Comment by estroz** [comment]
@Adirio the new functions LGTM!

**Review by camilamacedo86 — COMMENTED** [review]
+1. Feel free to make that a PR.

**Pull request closed without merging**
