### PR TITLE
:warning: remove config-gen alpha option

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Description

Remove alpha option config-gen

## Motivation

- Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/2999 (issue with deps)

- Potential vulnerability caused by the deps used on config-gen:
Screenshot 2022-10-05 at 13 19 13

- Improve the maintainability by removing the option since it requires a lot of dependencies and has no longer been adopted by the community. However, we would like to get help in to looking for persuading this approach to add a new plugin that would do the same (following the kubebuilder ecosystem) OR create a new project like kubegen which could use Kubebuilder as LIB and have this option by default. See: https://github.com/kubernetes-sigs/kubebuilder/issues/3000

### CODE REVIEW

**Comment by camilamacedo86** [comment]
/hold

For we are able to discuss.

**Comment by pwittrock** [comment]
Lgtm

**Comment by laxmikantbpandhare** [comment]
agree with this. I can see this issue and cannot do `go mod tidy`. @camilamacedo86 can we get it merged ASAP.

**Review by jmrodri — APPROVED** [review]
/lgtm

**Comment by jmrodri** [comment]
/approved

apidiff output reviewed, looks ok to me

**Review by everettraven — APPROVED** [review]
/lgtm

**Review by varshaprasad96 — APPROVED** [review]
We may have to remove this: https://book.kubebuilder.io/plugins/creating-plugins.html?highlight=config-gen#future-vision-for-kubebuilder-plugins, but we can do it in a follow up too.
/lgtm
/approve

**Comment by laxmikantbpandhare** [comment]
> We may have to remove this: https://book.kubebuilder.io/plugins/creating-plugins.html?highlight=config-gen#future-vision-for-kubebuilder-plugins, but we can do it in a follow up too. /lgtm /approve

Agree, will take a look into it.

**Comment by pwittrock** [comment]
/override "APIDiff / Verify API differences (pull_request) "

**Comment by laxmikantbpandhare** [comment]
thank you @pwittrock and @jmrodri

**Pull request merged**
