### PR TITLE
:seedling: Remove resetting of GOPATH while scaffolding test project

### PR DESCRIPTION
**Pull request by bvwells**
**Description**

Remove unnecessary resetting of GOPATH while scaffolding test project.

**Motivation**
Cleanup

### CODE REVIEW

**Comment by gabbifish** [comment]
Hi @bvwells! Thank you for this contribution :) Before I run the test suite on this, do you mind rebasing your PR on the tip of master? That should fix the Travis CI build error I see above.

**Comment by bvwells** [comment]
Hi @gabbifish, all rebased. Only a small change I noticed while having a look why kubebuilder has to be developed on GOAPTH. :-)

**Comment by camilamacedo86** [comment]
Hi @bvwells, 

It is missing the mojo in the title. See: https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md#pr-process. Could you please update it? Otherwise, it is for me 👍 

/approve 

Thank you for your contribution.

**Review by camilamacedo86 — APPROVED** [review]
👍

**Comment by bvwells** [comment]
Thanks @camilamacedo86! Sorry for missing the PR guidelines.

**Pull request merged**
