### PR TITLE
A small correction

### PR DESCRIPTION
**Pull request by ijmitch**
... I think you meant 'principles' in this case.

### CODE REVIEW

**Comment by ijmitch** [comment]
I probably need to sign the CLA with my work id - so if you want to reject this and just do it next time you're updating the file I'm fine with that.

**Comment by pwittrock** [comment]
@ijmitch thanks!  would you sign the cla?

**Comment by ijmitch** [comment]
I'm working through the IBM process for me to sign the CLA.

**Comment by ijmitch** [comment]
I've now signed the CLA as a member of 'CNCF - IBM'

**Pull request merged**
