### PR TITLE
Fix old link to envtest docs that should have been removed

### LINKED ISSUE #1621: docs: Controller-test doc page is render blank
See:  

Screenshot 2020-07-30 at 20 51 15

Note: it maybe or not can be related to the changes made in : https://github.com/kubernetes-sigs/kubebuilder/pull/1521

### PR DESCRIPTION
**Pull request by gabbifish**
This PR fixes #1621, which was caused by an old sidebar link that should have been deleted as part of moving the integration test example under the CronJob example section.

### CODE REVIEW

**Comment by camilamacedo86** [comment]
Hi @gabbifish, 

Really nice, following some nits.

- The link in https://deploy-preview-1624--kubebuilder.netlify.app/cronjob-tutorial/writing-tests.html shows not rigfht. See:

Screen Shot 2020-08-04 at 09 18 30

The name of the section is: `Configuring envtest for integration tests`. So, we need to update that. 

- Also, in the submenu after this change:

Screen Shot 2020-08-04 at 09 22 29

IMO it needs to be changed to be like the others. Maybe `Configuring Env Test`. WDYT?

**Comment by gabbifish** [comment]
Ooh, great catches! I addressed both bullet points--let me know what you think!

**Comment by camilamacedo86** [comment]
Hi @gabbifish, 

Could you rebase with the master and squash the commits for we are able to merge this one? 

/lgtm cancel

**Comment by gabbifish** [comment]
@camilamacedo86 rebased on master and squashed!

**Pull request merged**
