### PR TITLE
:book: fixes the missing scheme reference in the sample code 

### PR DESCRIPTION
**Pull request by naveensrinivasan**
**Description**
The `scheme` reference is missing in the sample code for the book. Without the `Scheme` the implementations could run into `panic` especially when using something like `SetControllerReference` which uses the `Scheme`.

### CODE REVIEW

**Review by camilamacedo86 — APPROVED** [review]
/lgtm
/approve 
/ok-to-test 

Thank you for the contribution 🥇

**Comment by camilamacedo86** [comment]
Hi @naveensrinivasan, 

Could you please rebase it with the master and push?

**Comment by naveensrinivasan** [comment]
@camilamacedo86  I have done that. Thanks

**Pull request merged**
