### PR TITLE
Upgrade book-v2 branch with v2.3.1 tag changes

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description**
Rebase the book-v2 branch with v2.3.1 tag release

**Motivation**
Ensure that all production docs in https://book.kubebuilder.io/ are properly updated and showing the code examples accordingly with the latest release.

### CODE REVIEW

**Comment by camilamacedo86** [comment]
/hold 

until @mengqiy approval/check.

**Comment by camilamacedo86** [comment]
/hold

Until get the confirmations and reviews.

**Comment by mengqiy** [comment]
Thanks for taking care of this!

**Pull request merged**
