### PR TITLE
:seedling: Bump golang.org/x/text to v0.3.7

### LINKED ISSUE #2437: Bump golang.org/x/text to v0.3.7
### What do you want to happen?

Kubebuilder has an indirect dependency on `golang.org/x/text@v0.3.6` which has a security bug ([GO-2021-0113](https://osv.dev/vulnerability/GO-2021-0113)). A fix was released a few months ago under version v0.3.7.

It would be good to have that dependency bumped up, so it is included on the next version released.

Details can be see on the project's [deps.dev](https://deps.dev/go/sigs.k8s.io%2Fkubebuilder%2Fv3/v3.2.0):
image

### Extra Labels

_No response_

### PR DESCRIPTION
**Pull request by pjbgf**
#### Description

Bump an indirect dependency to fix minor security advisory which was fixed a few months ago.
More information in the linked issue below.

 Fixes #2437

### CODE REVIEW

**Comment by pjbgf** [comment]
@camilamacedo86 following up the meeting today, would you mind taking a look at this PR please?

**Review by estroz — CHANGES_REQUESTED** [review]
AFAIK this won't actually change the version used by dependencies, and kubebuilder doesn't use this dep directly. Use a `replace` directive instead
```
replace golang.org/x/text => golang.org/x/text v0.3.7
```

**Comment by pjbgf** [comment]
@estroz I believe the difference between the two approaches is that one defines the minimum version of the indirect dependency, and the other replaces all references to it. 

For example, the current approach relies on golang [MVS](https://go.dev/ref/mod#minimal-version-selection) to find the minimum required version on `go.sum`, which in this case would be `v0.3.7`:

```
golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c/go.mod h1:NqM8EUOU14njkJ3fqMW+pc6Ldnwhi/IjpwHt7yyuwOQ=
golang.org/x/text v0.3.0/go.mod h1:NqM8EUOU14njkJ3fqMW+pc6Ldnwhi/IjpwHt7yyuwOQ=
golang.org/x/text v0.3.1-0.20180807135948-17ff2d5776d2/go.mod h1:NqM8EUOU14njkJ3fqMW+pc6Ldnwhi/IjpwHt7yyuwOQ=
golang.org/x/text v0.3.2/go.mod h1:bEr9sfX3Q8Zfm5fL9x+3itogRgK3+ptLWKqgva+5dAk=
...
golang.org/x/text v0.3.6/go.mod h1:5Zoc/QRtKVWzQhOtBMvqHzDpF6irO9z98xDceosuGiQ=
golang.org/x/text v0.3.7 h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
golang.org/x/text v0.3.7/go.mod h1:u+2+/6zg+i71rQMx5EYifcz6MCKuco9NR6JIITiCfzQ=
```

If we were to use replace instead (e.g. `replace golang.org/x/text => golang.org/x/text v0.3.7`), we would instead replace that with:

```
golang.org/x/text v0.3.7 h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
golang.org/x/text v0.3.7/go.mod h1:u+2+/6zg+i71rQMx5EYifcz6MCKuco9NR6JIITiCfzQ=
```
Meaning that in the future when our direct dependencies start requiring a version newer than that, it would be replaced by `v0.3.7`. This approach would act as a `pin` so to speak. 

Please let me know whether that's still the preferred approach and I will amend the PR accordingly. 

PS: This was already tested on [security-profiles-operator](https://github.com/kubernetes-sigs/security-profiles-operator) with the desired effect confirmed through [deps.dev](https://deps.dev/go/sigs.k8s.io%2Fsecurity-profiles-operator/v0.3.1-0.20211122222133-6e12fe5f2daa).

**Comment by camilamacedo86** [comment]
HI @rashmigottipati and @estroz, 

Following my review:

First, the mojo here would be `:seedling:` that is not a new feature.
I do not think that is the case to use the replace. 

However, why do we need to bump only this indirect dep?

Could we not just:
- Remove all indirect ones
- Bump go 1.17
- Run go mod tidy 

And then, update all indeed the go version which is a requirement tracked in the repo? Would not that make more sense?

**Comment by estroz** [comment]
@pjbgf I was not aware that `// indirect` declarations in `require` made a difference, but you are right
```console
$ go list -m all | grep golang.org/x/text
golang.org/x/text v0.3.7
```

I'm ok with this change. @camilamacedo86 in go 1.17 the indirect's are listed in a separate block so this won't be an eyesore after bumping go versions, so we can merge this then bump in a separate PR. Thoughts?

**Review by camilamacedo86 — APPROVED** [review]
/approved
/lgtm

For me @rashmigottipati @estroz

**Pull request merged**
