### PR TITLE
✨ (go/v3,go/v4-alpha): Upgrade controller-runtime version from 1.13.0 to  1.13.1

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Description

Upgrade controller-runtime version from 1.13.0 to  1.13.1

For further info, check the controller-runtime release notes.

### CODE REVIEW

**Review by Kavinjsir — APPROVED** [review]
Looks good to me

**Review by varshaprasad96 — COMMENTED** [review]
/lgtm
Do we need to bump anything in the docs? If not please feel free to approve and merge!

**Review by everettraven — APPROVED** [review]
/lgtm

I think we just need to override the failing checks? They seem to be expected failures

**Comment by camilamacedo86** [comment]
> Do we need to bump anything in the docs? If not please feel free to approve and merge!

About this bump. I do not think so, Why should we?

**Pull request merged**
