### PR TITLE
Build kubebuilder-tools v1.20.2

### PR DESCRIPTION
**Pull request by shysank**
Updates kubebuilder tools to version ~`1.20.1`~ `1.20.2`

### CODE REVIEW

**Comment by camilamacedo86** [comment]
Hi @shysank, 

Could you please check with @estroz? He works on the code that does the release a few time ago. I am not sure if this branch is used since it is diff from the master.

**Comment by shysank** [comment]
@camilamacedo86 Confirmed with @estroz that this is the right branch. Also, based on @estroz's suggestion, updated to `1.20.2` instead of `1.20.1` which got released recently.

**Pull request merged**
