### PR TITLE
🌱: Add prefix to bot PR title to respect community rule

### PR DESCRIPTION
**Pull request by Kavinjsir**
#### Description

Add a condition to skip PR Verifier if the PR is created by dependabot

#### Motivation

Current PRs created by dependabot fail the CI/CD workflows as the title of the PR does not match the community's criteria.
It seems dependabot does NOT provide an entry to configure the title, so I am thinking if we can just skip the PR verifier in such scenarios.

### CODE REVIEW

**Review by mateusoliveira43 — CHANGES_REQUESTED** [review]
Can not be this achieved by using this option https://github.com/migtools/oadp-non-admin/blob/master/.github/dependabot.yml#L10 ? i kubebuilder case, setting it to 🌱

**Comment by Kavinjsir** [comment]
> Can not be this achieved by using this option https://github.com/migtools/oadp-non-admin/blob/master/.github/dependabot.yml#L10 ? in kubebuilder case, setting it to 🌱

Great suggestion! Just applied that.

**Review by mateusoliveira43 — APPROVED** [review]
would just change PR title
LGTM

**Review by camilamacedo86 — APPROVED** [review]
That is great 🥇 

Thank you a lot

/approved
/lgtm
/ok-to-test

**Pull request merged**
