### PR TITLE
🌱added tests for version.go

### LINKED ISSUE #3211: Increase the test coverage with unit tests
### What do you want to happen?

By looking at the coveralls reports we can see that we have some implementations which could be better covered. We do not cover 100% of the code but would be great increase the coverage and ensure that we have no red and orange files/dirs, see: https://coveralls.io/github/kubernetes-sigs/kubebuilder?branch=master

Example: 

We could add more tests for cmd_helpers.go, completiton.go and version.go:

Screenshot 2023-02-08 at 14 17 13

### Extra Labels

_No response_

### PR DESCRIPTION
**Pull request by khareyash05**
added tests for `pkg/cli/version.go`

Fixes #3211

### CODE REVIEW

**Comment by khareyash05** [comment]
@camilamacedo86 Could you please help me with this error? I am not able to understand what's wrong in my code

**Comment by NikhilSharmaWe** [comment]
@khareyash05 https://github.com/kubernetes-sigs/kubebuilder/pull/3374 should fix the error you are getting in this PR. So, let's wait till it gets merged.

**Comment by khareyash05** [comment]
Thank you @NikhilSharmaWe

**Pull request closed without merging**
