### PR TITLE
Update book README, fix a typo and formatting

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

Before: 
before

After:
after

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
I'm not sure but I think the test error is not my fault?

```
3:49:55 PM: npm ERR!
3:49:55 PM: code EINTEGRITY
3:49:55 PM: npm ERR! Verification failed while extracting lodash@4.17.5:
3:49:55 PM: npm ERR! Verification failed while extracting lodash@4.17.5:
3:49:55 PM: npm ERR! sha1-K9bcRqBA9Z5obJcu0h2T3FkFMlg= integrity checksum failed when using sha1: wanted sha1-K9bcRqBA9Z5obJcu0h2T3FkFMlg= but got sha512-svL3uiZf1RwhH+cWrfZn3A4+U58wbP0tGVTLQPbjplZxZ8ROD9VLuNgsRniTlLe7OlSqR79RUehXgpBW/s0IQw== sha1-maktZcAnLevoyWtgV7yPv6O+1RE=. (305530 bytes)
```

**Comment by stevekuznetsov** [comment]
@DirectXMan12 any thoughts?

**Comment by mengqiy** [comment]
@stevekuznetsov  Please rebase.
Generated files under `docs/book/_book` are no longer needed.

**Comment by stevekuznetsov** [comment]
@mengqiy ok! sone

**Pull request merged**
