### PR TITLE
📖 remove duplicated entry [plugin-subc], [plugin-sub-command] is the one being used

### PR DESCRIPTION
**Pull request by monteiro-renato**

### CODE REVIEW

**Review by camilamacedo86 — APPROVED** [review]
/lgtm
/approve
/ok-to-test

**Comment by camilamacedo86** [comment]
@monteiro-renato 

This one we will need to rebase with master sorry
can you please re-base and re-sent it?

**Comment by monteiro-renato** [comment]
Done!

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Comment by camilamacedo86** [comment]
Hi @monteiro-renato 

this one we will need a rebase

**Pull request merged**
