### PR TITLE
:book: update prerequisites to clarifies go versions which are supported

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description**
📖 Update go version information in the QuickStart Prerequisites

**Motivation** 
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/2543

### CODE REVIEW

**Comment by coderanger** [comment]
-1 on making this so specific. We can certainly recommend versions that are tested with but I don't think this reflects the reality of what versions are supported.

**Comment by camilamacedo86** [comment]
Hi @coderanger,

We can only support these specific versions. 
We do not test all ensure it with all versions and indeed unfortunately we cannot make the project does work in many scenarios when users do not use the supported Golang versions since has breaking changes. E.g. Go 1.18 will not work with the latest release at all since go get was deprecated and no longer available in 1.18. 

these are the versions that we can support, however, users still able to use any other version as please them.

**Comment by AlmogBaku** [comment]
I'm with @camilamacedo86 here. Declaring the versions which are *supported* means that this is what the team has identified as potentially broken. You are always welcome to challenge it, but this is not what we recommend.

/lgtm

**Review by AlmogBaku — APPROVED** [review]

**Comment by camilamacedo86** [comment]
By thinking deeper here.
Why we are adding the min/ max go version for each bin released?
In the doc we try to keep the state/info only about the latest release/master

So, that makes no sense. We actually should only have now GO >= 17 and <=18
We are bumping GO 1.18 so we might solve this scenario. 

c/c @AlmogBaku

**Pull request closed without merging**
