### PR TITLE
🌱 E2E tests cleanup

### PR DESCRIPTION
**Pull request by Adirio**
Cleanup e2e tests:
- Remove duplicated code.
- Use `Expect(...).To(Succeed())` for function calls and `Expect(err).NotTo(HaveOcurred())` for error checkings as in the rest of the repo.

### CODE REVIEW

**Comment by Adirio** [comment]
/hold

Holding instead of using a draft PR as e2e tests need to be run.

**Comment by camilamacedo86** [comment]
Hi @Adirio, 

This PR is open for a while and requires rebased. It is flagged with  /lifecycle stale already.
It is harder to help with the reviews when we have a lot of PRs open. 

I believe that you are without time to work on it. So, I hope that is fine we close this one for now. 
However, please feel free to re-open if you be able to address the requirements here for we move forward and ping me for we get it merged.

**Pull request closed without merging**
