### PR TITLE
Unused parameters replacement by blank identifier

### PR DESCRIPTION
**Pull request by Adirio**
### References:
- [Blank identifier](https://golang.org/doc/effective_go.html#blank)
- [Blank Identifier for unused variables](https://golang.org/doc/effective_go.html#blank_unused)

Closes: #1179

/kind cleanup

### CODE REVIEW

**Comment by Adirio** [comment]
Rebase done

/test pull-kubebuilder-e2e

**Comment by mengqiy** [comment]
Don't worry about pull-kubebuilder-e2e, it's WIP.
/lgtm
/approve

**Pull request merged**
