### PR TITLE
plugins: merge with master

### PR DESCRIPTION
**Pull request by estroz**
Had to close #1461 because travis wasn't triggering. Seems to be a result of their GCP issues last week.

Conflict diffs:
<details>
<summary>Only one conflict with the addition of newCompletionCmd()</summary>

```diff
+		cli.WithExtraCommands(
+			newEditCmd(),
+			newUpdateCmd(),
+			newCompletionCmd(),
+			version.NewCmd(),
+		),
+	)
+	if err != nil {
+		log.Fatal(err)
+	}
+	if err := c.Run(); err != nil {
-
-
-	// kubebuilder version
-	rootCmd.AddCommand(version.NewVersionCmd())
-
-	// kubebuilder completion
-	rootCmd.AddCommand(newCompletionCmd())
-
-	return rootCmd
-}
-
-func main() {
-	if err := buildCmdTree().Execute(); err != nil {
		log.Fatal(err)
```
</details>

/cc @camilamacedo86 @Adirio @DirectXMan12

### CODE REVIEW

**Comment by estroz** [comment]
Going to close this and re-merge once #1448 is merged. Perhaps travis will work on that PR *sigh*.

**Comment by estroz** [comment]
https://travis-ci.org/github/kubernetes-sigs/kubebuilder/builds/672842403

**Comment by camilamacedo86** [comment]
/lgtm 
👍

**Pull request merged**
