### PR TITLE
Use zap.New instead of zap.LoggerTo because of deprecated

### PR DESCRIPTION
**Pull request by micnncim**
`zap.LoggerTo` has been deprecated so it needs to use `zap.New`.

fixes:  #1105

### Reference

- https://github.com/kubernetes-sigs/kubebuilder/pull/1101
- https://github.com/kubernetes-sigs/controller-runtime/pull/646
- https://github.com/kubernetes-sigs/controller-runtime/pull/639

### CODE REVIEW

**Comment by Adirio** [comment]
Travis is failing due to `golden_test.sh` not being run. Run `./generate_golden.sh` on a non-Windows machine.

**Comment by camilamacedo86** [comment]
Hi micnncim,

Could you also rebase this with the master branch?

**Comment by micnncim** [comment]
Sorry for the late reply, I'll work on that!

**Comment by DirectXMan12** [comment]
We've got helpers now in CR, so once we do the CR release we can get this in

**Comment by Adirio** [comment]
@DirectXMan12 is this still waiting for CR or does the 0.4.0 version already have the mentioned helpers?

**Comment by camilamacedo86** [comment]
Hi @micnncim, 

Could you please rebase it with the master branch and run the command `make generate` in order to ensure that the golden script will be exec with the proper setup as well?

**Comment by Adirio** [comment]
@micnncim I think you should be using these helpers: 

https://github.com/kubernetes-sigs/controller-runtime/blob/5e2c4c885d68f1282531f42dc9cecc908ad5da3f/pkg/log/zap/zap.go#L78

https://github.com/kubernetes-sigs/controller-runtime/blob/5e2c4c885d68f1282531f42dc9cecc908ad5da3f/pkg/log/zap/zap.go#L86

**Comment by micnncim** [comment]
@camilamacedo86 Have rebased and generated testdata by `make generate`. Thank you for instruction.

**Comment by micnncim** [comment]
@Adirio Thank you for your advice 👍 It's very helpful for me.

**Comment by camilamacedo86** [comment]
Hi @micnncim, 

Shows that it still not passing in the golden test. So, ensure that it is rebased with the master and run the `make generated` (it will not work in a win platform).

**Comment by mengqiy** [comment]
IIRC we are waiting for a new controller-runtime release and then merge this PR, since we are going to have some code depend on some new helper code in controller-runtime.

**Comment by camilamacedo86** [comment]
Hi @micnncim, 

It is requiring a rebase with the master. Could you please do that for the @mengqiy or @DirectXMan12 be able to approve/merge this one?

**Comment by micnncim** [comment]
Rebased.

**Comment by Adirio** [comment]
@mengqiy @DirectXMan12 cr-0.5.0 came out and the helpers are the same as of cr-0.4.0 (I think that https://github.com/kubernetes-sigs/kubebuilder/pull/1116#issuecomment-553987084 was talking about cr-0.4.0 that came out one day after that comment).

Can this be merged?

**Comment by mengqiy** [comment]
@micnncim Can you squash the commits please? This can be merged then.

**Comment by mengqiy** [comment]
closes: #1105

**Comment by micnncim** [comment]
Sorry, I made a mistake when I rebased the commits. I'm fixing now.

**Comment by micnncim** [comment]
I create the port of this PR https://github.com/kubernetes-sigs/kubebuilder/pull/1385 for convenience. So could you check the PR instead of this? If it's OK, I'll close this PR. I apologize for that.

**Comment by camilamacedo86** [comment]
/close 

We can close this one since you did the #1385 instead of the rebase to address the same changes.

**Pull request closed without merging**
