### PR TITLE
Ship arm64 and ppc64le binaries

### PR DESCRIPTION
**Pull request by mkumatag**
Fixes: https://github.com/kubernetes-sigs/kubebuilder/issues/966

### CODE REVIEW

**Comment by DirectXMan12** [comment]
This'll ship the actual KB binary, but not the control plane (so no tests).

Also, we don't have CI for this.  Can you confirm that you've built this and it works?

**Comment by mkumatag** [comment]
> This'll ship the actual KB binary, but not the control plane (so no tests).
> 
> Also, we don't have CI for this. Can you confirm that you've built this and it works?

I just built and tetsted the `kubebuilder` on ppc64le platform and it works, here is my result:

```shell
root@localhost:~/kubebuilder_ws/src/sigs.k8s.io/kubebuilder/dist# ls -l
total 18608
-rw-r--r-- 1 root root     427 Sep  3 09:47 CHANGELOG.md
-r--r--r-- 1 root root     415 Sep  3 09:48 checksums.txt
-rw-r--r-- 1 root root    2398 Sep  3 09:47 config.yaml
-rw-r--r-- 1 root root 7113505 Sep  3 09:48 kubebuilder_2.0.0_darwin_amd64.tar.gz
-rw-r--r-- 1 root root 4203283 Sep  3 09:48 kubebuilder_2.0.0_linux_amd64.tar.gz
-rw-r--r-- 1 root root 3880298 Sep  3 09:48 kubebuilder_2.0.0_linux_arm64.tar.gz
-rw-r--r-- 1 root root 3817757 Sep  3 09:48 kubebuilder_2.0.0_linux_ppc64le.tar.gz
drwxr-xr-x 2 root root    4096 Sep  3 09:48 kubebuilder_darwin_amd64
drwxr-xr-x 2 root root    4096 Sep  3 09:48 kubebuilder_linux_amd64
drwxr-xr-x 2 root root    4096 Sep  3 09:48 kubebuilder_linux_arm64
drwxr-xr-x 5 root root    4096 Sep  3 09:50 kubebuilder_linux_ppc64le
root@localhost:~/kubebuilder_ws/src/sigs.k8s.io/kubebuilder/dist#
root@localhost:~/kubebuilder_ws/src/sigs.k8s.io/kubebuilder/dist# cd kubebuilder_linux_ppc64le/
root@localhost:~/kubebuilder_ws/src/sigs.k8s.io/kubebuilder/dist/kubebuilder_linux_ppc64le# file kubebuilder
kubebuilder: ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), statically linked, stripped
root@localhost:~/kubebuilder_ws/src/sigs.k8s.io/kubebuilder/dist/kubebuilder_linux_ppc64le#
root@localhost:~/kubebuilder_ws/src/sigs.k8s.io/kubebuilder/dist/kubebuilder_linux_ppc64le# ./kubebuilder init --domain example.com --license apache2 --owner "The Kubernetes authors"
go mod tidy
go: finding sigs.k8s.io/controller-runtime v0.2.0
go: finding github.com/onsi/gomega v1.4.2
go: finding github.com/googleapis/gnostic v0.2.0
go: finding github.com/golang/groupcache v0.0.0-20180513044358-24b0969c4cb7
…..
……
root@localhost:~/kubebuilder_ws/src/sigs.k8s.io/kubebuilder/dist/kubebuilder_linux_ppc64le# ls -l
total 10180
-rw------- 1 root root      774 Sep  3 09:49 Dockerfile
-rw------- 1 root root     1813 Sep  3 09:49 Makefile
-rw------- 1 root root       63 Sep  3 09:49 PROJECT
drwxr-xr-x 2 root root     4096 Sep  3 09:50 bin
drwx------ 7 root root     4096 Sep  3 09:49 config
-rw------- 1 root root      266 Sep  3 09:49 go.mod
-rw------- 1 root root    15667 Sep  3 09:49 go.sum
drwx------ 2 root root     4096 Sep  3 09:49 hack
-rwxr-xr-x 1 root root 10461088 Sep  3 09:48 kubebuilder
-rw------- 1 root root     1912 Sep  3 09:49 main.go
root@localhost:~/kubebuilder_ws/src/sigs.k8s.io/kubebuilder/dist/kubebuilder_linux_ppc64le#
```

**Comment by DirectXMan12** [comment]
neato

@droot @mengqiy any comments?  This seems good to me, and we can follow up with building test binaries

**Comment by mengqiy** [comment]
LGTM
/cc @droot

**Pull request merged**
