### PR TITLE
OWNERS: add estroz to reviewers

### PR DESCRIPTION
**Pull request by estroz**
/cc @DirectXMan12

### CODE REVIEW

**Comment by DirectXMan12** [comment]
Are you in k or k-sigs yet?  If not, let's sponsor you in :-)

**Comment by estroz** [comment]
@DirectXMan12 not yet.

**Comment by DirectXMan12** [comment]
file an issue in k/org and I'm happy to sponsor you (and I'm sure you can get another RH-er to sponsor you too ;-) ).

**Comment by estroz** [comment]
https://github.com/kubernetes/org/issues/1466

**Comment by DirectXMan12** [comment]
/lgtm
/approve

welcome aboard :ship:

**Comment by DirectXMan12** [comment]
@estroz ping me when you accept your org invite an I'll make sure this merges

**Comment by estroz** [comment]
@DirectXMan12 thanks, I’m in the org.

**Pull request merged**
