### PR TITLE
🐛(kustomize/v2, go/v4, deploy-image/v1-alpha): Fix labels according to conventions and conveys. app.kubernetes.io/name now have the ProjectName and the labels app.kubernetes.io/instance, app.kubernetes.io/component, app.kubernetes.io/created-by, app.kubernetes.io/part-of were removed

### PR DESCRIPTION
**Pull request by sarthaksarthak9**
- updates the labels to project naming conventions as suggested. It removes unnecessary labels according to project guidelines. 
- The changes ensure consistency and alignment with project standards. 
-  #3783

### CODE REVIEW

**Review by camilamacedo86 — APPROVED** [review]
Thank you for the contribution 🥇 

It shows excellent for me 👍 
/approved


@joelanford, since you requested this one, would you like to look at it? Please feel free to lgtm to get it if you are OKmerged.

**Comment by sarthaksarthak9** [comment]
> Thank you for the contribution 🥇
> 
> It shows excellent for me 👍 /approved
> 
> @joelanford, since you requested this one, would you like to look at it? Please feel free to lgtm to get it if you are OKmerged.

Thank you for showing patience and guiding me

**Comment by camilamacedo86** [comment]
Hi @sarthaksarthak9 

Thank you for your amazing work and for your contribution 🥇

**Pull request merged**
