### PR TITLE
:warning: deprecate declarative plugin

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Description:

This PR deprecates the declarative plugin and adds the following notice:

Screenshot 2023-05-08 at 09 40 27

Also, we are:
- Updating the docs to make clear that it is deprecated
- Removing the sample under test data to stop to block us from moving forward with upgrades, such as now that we want to bump controller runtime alpha 0.15 and it will fail in : https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kubebuilder/3394/pull-kubebuilder-test/1655479526613848064

Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/3186
Related to : https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/293

### CODE REVIEW

**Comment by varshaprasad96** [comment]
@camilamacedo86 I'm fine moving ahead with the PR. Just want to confirm if Kubebuilder declarative pattern maintainers are comfortable with us doing this, or would like to first externalize the plugin and then deprecate (followed by remove) it. cc: @justinsb

**Comment by camilamacedo86** [comment]
Hi @varshaprasad96, 

> @camilamacedo86 I'm fine moving ahead with the PR. Just want to confirm if Kubebuilder declarative pattern maintainers are comfortable with us doing this, or would like to first externalize the plugin and then deprecate (followed by remove) it. cc: @justinsb

I wholeheartedly concur, and I'm also eager to hear their thoughts. However, let me shed some light on my main reasons for pushing this:

- a) We need to continue making changes in the declarative project until we can deprecate and remove these tests and samples, as done in the PR. Without doing so, we run the risk of being blocked from updating k8s and controller runtime. (as we are now)
- b) It's important that we deprecate this as soon as possible. We have a number of deprecations ongoing, and this is the last one needed to clean up Kubebuilder and make its maintenance easier. I believe we should aim to complete all deprecations as soon as possible. This way, we can stop supporting those deprecated features and plan to release Kubebuilder 4.x in line with the k8s 1.28 or 1.29 updates at the latest.

Thank you a lot for all your understanding and input!!!

**Review by Kavinjsir — APPROVED** [review]
Nits:
we may also remove:
1. https://github.com/kubernetes-sigs/kubebuilder/blob/7711b8f84067ff04fe4dc5dc0213c76bb8e9d14a/docs/book/src/SUMMARY.md?plain=1#L122
2. https://github.com/kubernetes-sigs/kubebuilder/blob/7711b8f84067ff04fe4dc5dc0213c76bb8e9d14a/docs/book/src/reference/project-config.md?plain=1#L87
3. https://github.com/kubernetes-sigs/kubebuilder/blob/7711b8f84067ff04fe4dc5dc0213c76bb8e9d14a/docs/book/src/plugins/to-be-extended.md?plain=1#L24
4. https://github.com/kubernetes-sigs/kubebuilder/blob/7711b8f84067ff04fe4dc5dc0213c76bb8e9d14a/docs/book/src/plugins/extending-cli.md?plain=1#L61

**Review by everettraven — APPROVED** [review]
/lgtm

**Review by Kavinjsir — APPROVED** [review]
lgtm 👍🏼

**Pull request merged**
