### PR TITLE
📖  Update cert-manager install url because it changed

### PR DESCRIPTION
**Pull request by rocrisp**
Pretty much what the title says.
The outdated link has been replaced with an new link.

### CODE REVIEW

**Review by estroz — COMMENTED** [review]
/ok-to-test
/approve
/lgtm

**Comment by estroz** [comment]
@rocrisp you need to sign the CLA too

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Comment by camilamacedo86** [comment]
hi @rocrisp,

Could you please  check `cla/linuxfoundation — rocrisp needs CLA`, we cannot merge without it pass.

**Comment by rocrisp** [comment]
I signed it

**Pull request merged**
