### PR TITLE
Golangci lint fixes for scaffold projects

### PR DESCRIPTION
**Pull request by LalatenduMohanty**

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
This PR is perquisite for https://github.com/kubernetes-sigs/kubebuilder/pull/805  cc @droot

**Comment by droot** [comment]
Sorry for the delay in reviewing it @LalatenduMohanty I don't see the changes for `project-v2` (project-version 2). Do you plan to do it separate commit ?

**Comment by LalatenduMohanty** [comment]
> Sorry for the delay in reviewing it @LalatenduMohanty I don't see the changes for `project-v2` (project-version 2). Do you plan to do it separate commit ?

@droot Looks like https://github.com/kubernetes-sigs/kubebuilder/tree/master/pkg/scaffold/v2 does not need any changes for golangci-lint. For testing purpose I have combined these commits in #805 and `./test.sh` is passing in my local test.

**Comment by camilamacedo86** [comment]
Hi @LalatenduMohanty, 

Shows that it is missing be rebased with the master.

**Pull request closed without merging**
