### PR TITLE
✨ Update envtest version (1.24.2 -> 1.25.0)

### PR DESCRIPTION
**Pull request by oscr**
* Updates envtest version 1.24.2 -> 1.25.0
* Updates kind version 0.14.0 -> 0.15.0

### CODE REVIEW

**Review by camilamacedo86 — APPROVED** [review]
It is not failng so I am OK in approve 
But usually we bump all in the same PR
controller-tools
controller-runtime
declarative bump
to ensure that all deps will be using k8s 1.25 as well. 

Could we do the rest in a follow-up @oscr ?

**Comment by oscr** [comment]
@camilamacedo86 No problem at all. I will fix it.

**Comment by oscr** [comment]
And thank you for your help and for the quick review :pray:

**Review by everettraven — APPROVED** [review]
/lgtm

**Pull request merged**
