### PR TITLE
✨ chore: add ginkgolinter

### PR DESCRIPTION
**Pull request by PG2000**
In order to have checks for some common errors in test files 
this enables the built-in ginkgolinter.

### CODE REVIEW

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

Thank you for the contribution 🥇 

I think we also need to add to Kubebuilder code

Can you please add it to: https://github.com/kubernetes-sigs/kubebuilder/blob/master/.golangci.yml

**Comment by PG2000** [comment]
> Thank you for the contribution 🥇
> 
> I think we also need to:
> 
>     * a) add to Kubebuilder code
> 
> 
> Can you please add it to: https://github.com/kubernetes-sigs/kubebuilder/blob/master/.golangci.yml
> 
>     * b) After any change in the scaffolds we MUST to run make generate.
>       This PR will fail in the check testdata sample since the samples under testdata and used for the docs are not updated with the change.

Done.

**Review by camilamacedo86 — COMMENTED** [review]
It still missing:

a) You run make generate so that your changes are applied in the samples
b) Please squash all commits so that we can get it merge

**Comment by PG2000** [comment]
Unfortunately `make generate` does not work from my machines. Both are Macs (Intel and M1).
Any hint for this.

 <details>
<summary>Console ouput</summary>

```bash
➜  kubebuilder git:(patch-1) ✗ make generate
go: creating new go.mod: module sigs.k8s.io/kubebuilder/testdata/project-v2
[Deprecation Notice] This version is deprecated and is no longer scaffolded by default since `28 Apr 2021`.The `go/v2` plugin cannot scaffold projects in which CRDs and/or Webhooks have a `v1` API version.Be aware that v1beta1 API for CRDs and Webhooks was deprecated on Kubernetes 1.16 and areremoved as of the Kubernetes 1.22 release. Therefore, since this plugin cannot produce projects thatwork on Kubernetes versions >= 1.22, it is recommended to upgrade your project to the latest versions available.

INFO Writing scaffold for you to edit...          
INFO Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.6.4
INFO Update dependencies:
$ go mod tidy           
[Deprecation Notice] This version is deprecated and is no longer scaffolded by default since `28 Apr 2021`.The `go/v2` plugin cannot scaffold projects in which CRDs and/or Webhooks have a `v1` API version.Be aware that v1beta1 API for CRDs and Webhooks was deprecated on Kubernetes 1.16 and areremoved as of the Kubernetes 1.22 release. Therefore, since this plugin cannot produce projects thatwork on Kubernetes versions >= 1.22, it is recommended to upgrade your project to the latest versions available.

INFO Writing scaffold for you to edit...          
INFO api/v1/captain_types.go                      
INFO controllers/captain_controller.go            
INFO Update dependencies:
$ go mod tidy           
[Deprecation Notice] This version is deprecated and is no longer scaffolded by default since `28 Apr 2021`.The `go/v2` plugin cannot scaffold projects in which CRDs and/or Webhooks have a `v1` API version.Be aware that v1beta1 API for CRDs and Webhooks was deprecated on Kubernetes 1.16 and areremoved as of the Kubernetes 1.22 release. Therefore, since this plugin cannot produce projects thatwork on Kubernetes versions >= 1.22, it is recommended to upgrade your project to the latest versions available.

INFO Writing scaffold for you to edit...          
INFO api/v1/captain_types.go                      
INFO controllers/captain_controller.go            
INFO Update dependencies:
$ go mod tidy           
[Deprecation Notice] This version is deprecated and is no longer scaffolded by default since `28 Apr 2021`.The `go/v2` plugin cannot scaffold projects in which CRDs and/or Webhooks have a `v1` API version.Be aware that v1beta1 API for CRDs and Webhooks was deprecated on Kubernetes 1.16 and areremoved as of the Kubernetes 1.22 release. Therefore, since this plugin cannot produce projects thatwork on Kubernetes versions >= 1.22, it is recommended to upgrade your project to the latest versions available.

INFO Writing scaffold for you to edit...          
INFO api/v1/captain_webhook.go                    
[Deprecation Notice] This version is deprecated and is no longer scaffolded by default since `28 Apr 2021`.The `go/v2` plugin cannot scaffold projects in which CRDs and/or Webhooks have a `v1` API version.Be aware that v1beta1 API for CRDs and Webhooks was deprecated on Kubernetes 1.16 and areremoved as of the Kubernetes 1.22 release. Therefore, since this plugin cannot produce projects thatwork on Kubernetes versions >= 1.22, it is recommended to upgrade your project to the latest versions available.

INFO Writing scaffold for you to edit...          
INFO api/v1/firstmate_types.go                    
INFO controllers/firstmate_controller.go          
INFO Update dependencies:
$ go mod tidy           
[Deprecation Notice] This version is deprecated and is no longer scaffolded by default since `28 Apr 2021`.The `go/v2` plugin cannot scaffold projects in which CRDs and/or Webhooks have a `v1` API version.Be aware that v1beta1 API for CRDs and Webhooks was deprecated on Kubernetes 1.16 and areremoved as of the Kubernetes 1.22 release. Therefore, since this plugin cannot produce projects thatwork on Kubernetes versions >= 1.22, it is recommended to upgrade your project to the latest versions available.

INFO Writing scaffold for you to edit...          
INFO api/v1/firstmate_webhook.go                  
[Deprecation Notice] This version is deprecated and is no longer scaffolded by default since `28 Apr 2021`.The `go/v2` plugin cannot scaffold projects in which CRDs and/or Webhooks have a `v1` API version.Be aware that v1beta1 API for CRDs and Webhooks was deprecated on Kubernetes 1.16 and areremoved as of the Kubernetes 1.22 release. Therefore, since this plugin cannot produce projects thatwork on Kubernetes versions >= 1.22, it is recommended to upgrade your project to the latest versions available.

INFO Writing scaffold for you to edit...          
INFO api/v1/admiral_types.go                      
INFO controllers/admiral_controller.go            
INFO Update dependencies:
$ go mod tidy           
[Deprecation Notice] This version is deprecated and is no longer scaffolded by default since `28 Apr 2021`.The `go/v2` plugin cannot scaffold projects in which CRDs and/or Webhooks have a `v1` API version.Be aware that v1beta1 API for CRDs and Webhooks was deprecated on Kubernetes 1.16 and areremoved as of the Kubernetes 1.22 release. Therefore, since this plugin cannot produce projects thatwork on Kubernetes versions >= 1.22, it is recommended to upgrade your project to the latest versions available.

INFO Writing scaffold for you to edit...          
INFO api/v1/admiral_webhook.go                    
[Deprecation Notice] This version is deprecated and is no longer scaffolded by default since `28 Apr 2021`.The `go/v2` plugin cannot scaffold projects in which CRDs and/or Webhooks have a `v1` API version.Be aware that v1beta1 API for CRDs and Webhooks was deprecated on Kubernetes 1.16 and areremoved as of the Kubernetes 1.22 release. Therefore, since this plugin cannot produce projects thatwork on Kubernetes versions >= 1.22, it is recommended to upgrade your project to the latest versions available.

INFO Writing scaffold for you to edit...          
INFO controllers/laker_controller.go              
INFO Update dependencies:
$ go mod tidy           
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x59c72de]

goroutine 121 [running]:
go/types.(*Checker).handleBailout(0xc0002a8c00, 0xc000a33d40)
/usr/local/Cellar/go/1.22.0/libexec/src/go/types/check.go:367 +0x88
panic({0x5c887c0?, 0x6204200?})
/usr/local/Cellar/go/1.22.0/libexec/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0x5d4abc8, 0x620c460})
/usr/local/Cellar/go/1.22.0/libexec/src/go/types/sizes.go:228 +0x31e
go/types.(*Config).sizeof(...)
/usr/local/Cellar/go/1.22.0/libexec/src/go/types/sizes.go:333
go/types.representableConst.func1({0x5d4abc8?, 0x620c460?})
/usr/local/Cellar/go/1.22.0/libexec/src/go/types/const.go:76 +0x9e
go/types.representableConst({0x5d50998, 0x61d9380}, 0xc0002a8c00, 0x620c460, 0x0)
/usr/local/Cellar/go/1.22.0/libexec/src/go/types/const.go:92 +0x192
go/types.(*Checker).arrayLength(0xc0002a8c00, {0x5d4ee70, 0xc000a6db80?})
/usr/local/Cellar/go/1.22.0/libexec/src/go/types/typexpr.go:510 +0x2d3
go/types.(*Checker).typInternal(0xc0002a8c00, {0x5d4d760, 0xc000f26a80}, 0x0)
/usr/local/Cellar/go/1.22.0/libexec/src/go/types/typexpr.go:299 +0x49d
go/types.(*Checker).definedType(0xc0002a8c00, {0x5d4d760, 0xc000f26a80}, 0xc000a33328?)
/usr/local/Cellar/go/1.22.0/libexec/src/go/types/typexpr.go:180 +0x37
go/types.(*Checker).varType(0xc0002a8c00, {0x5d4d760, 0xc000f26a80})
/usr/local/Cellar/go/1.22.0/libexec/src/go/types/typexpr.go:145 +0x25
go/types.(*Checker).structType(0xc0002a8c00, 0xc000f3ca50, 0xc000f3ca50?)
/usr/local/Cellar/go/1.22.0/libexec/src/go/types/struct.go:113 +0x19f
go/types.(*Checker).typInternal(0xc0002a8c00, {0x5d4d6d0, 0xc000ae5a40}, 0xc000f24ff0)
/usr/local/Cellar/go/1.22.0/libexec/src/go/types/typexpr.go:316 +0x1345
go/types.(*Checker).definedType(0xc0002a8c00, {0x5d4d6d0, 0xc000ae5a40}, 0x5ae17d0?)
/usr/local/Cellar/go/1.22.0/libexec/src/go/types/typexpr.go:180 +0x37
go/types.(*Checker).typeDecl(0xc0002a8c00, 0xc000f24ff0, 0xc000f32100, 0x0)
/usr/local/Cellar/go/1.22.0/libexec/src/go/types/decl.go:615 +0x44d
go/types.(*Checker).objDecl(0xc0002a8c00, {0x5d55758, 0xc000f24ff0}, 0x0)
/usr/local/Cellar/go/1.22.0/libexec/src/go/types/decl.go:197 +0xa7f
go/types.(*Checker).packageObjects(0xc0002a8c00)
/usr/local/Cellar/go/1.22.0/libexec/src/go/types/resolver.go:681 +0x425
go/types.(*Checker).checkFiles(0xc0002a8c00, {0xc001080708, 0x3, 0x3})
/usr/local/Cellar/go/1.22.0/libexec/src/go/types/check.go:408 +0x1a5
go/types.(*Checker).Files(...)
/usr/local/Cellar/go/1.22.0/libexec/src/go/types/check.go:372
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck(0xc0001fa990, 0xc000e7fae0)
/Users/pg2000/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/loader/loader.go:283 +0x35b
sigs.k8s.io/controller-tools/pkg/loader.(*Package).NeedTypesInfo(0xc000e7fae0)
/Users/pg2000/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/loader/loader.go:96 +0x39
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc000b92450, 0xc000e7fae0)
/Users/pg2000/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/loader/refs.go:249 +0x277
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0x59?)
/Users/pg2000/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/loader/refs.go:243 +0x53
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check in goroutine 83
/Users/pg2000/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/loader/refs.go:241 +0x18c
make[1]: *** [generate] Error 2
make: *** [generate-testdata] Error 2
➜  kubebuilder git:(patch-1) ✗ 
```
</details>

**Comment by camilamacedo86** [comment]
Hi @PG2000 

>Unfortunately make generate does not work from my machines. Both are Macs (Intel and M1).
Any hint for this.

I do not have a M1, however, it should work well as well.
The make generate will just bin the binary, and use it to re-generate the samples and update the docs.
Therefore, at the same way that you are able to use Kubebuilder CLI in your machine it only automates the usage operations with a bin built from your local env/wth the changes.

it has no reason for it does not work at all.
if you are facing an issue, could you please raise an issue with the details?

**Review by camilamacedo86 — COMMENTED** [review]
Can you please squash the commits and rebase?

**Review by camilamacedo86 — COMMENTED** [review]
Missing rebase, squash and run make generate

**Comment by PG2000** [comment]
> Can you please squash the commits and rebase?

done. Fortunately the make generate works now.

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Review by camilamacedo86 — COMMENTED** [review]
@PG2000 

Cool now you can check the lint erros.
We need to fix them in this PR to get it merged

You can run locally make lint as well to do the tests.

**Comment by PG2000** [comment]
> @PG2000
> 
> Cool now you can check the lint erros. We need to fix them in this PR to get it merged
> 
> You can run locally make lint as well to do the tests.

done

**Review by camilamacedo86 — COMMENTED** [review]
/lgtm

**Pull request merged**
