### PR TITLE
✨ bump controller-runtime and K8s 1.27

### PR DESCRIPTION
**Pull request by kkkkun**
bump controller-runtime to v0.15.0-beta.0

Partial : https://github.com/kubernetes-sigs/kubebuilder/issues/3376

xref: https://github.com/kubernetes-sigs/kubebuilder/pull/3421

### CODE REVIEW

**Comment by kkkkun** [comment]
The tests are paased. @camilamacedo86

**Comment by camilamacedo86** [comment]
Blocked by: https://github.com/kubernetes-sigs/kubebuilder/pull/3442

We getting this one merged we can rebase it with the master and ensure that this PR does not have this change. 
So I would suggest yoy
- First remove the commit with the changes of the above PR: ( you can use git rebase i HEAD~3)
- Then, rebase it with the master

**Comment by camilamacedo86** [comment]
HI @kkkkun, 

That is a great job. 

Could you please rebase the commits for we get this one merged?

**Comment by kkkkun** [comment]
> HI @kkkkun,
> 
> That is a great job.
> 
> Could you please rebase the commits for we get this one merged?

It's already rebase from master. you can see https://github.com/kkkkun/kubebuilder/commits/bump-controller-runtime

**Review by camilamacedo86 — APPROVED** [review]
I am approving this one but we need squash it to have just one commit before merge. 
Thank you a lot.

**Comment by kkkkun** [comment]
> I am approving this one but we need squash it to have just one commit before merge. Thank you a lot.

Thank you. Done.

**Comment by kkkkun** [comment]
It's strange, I just squash and this test is failed. https://github.com/kubernetes-sigs/kubebuilder/actions/runs/5252346422/jobs/9488444816?pr=3444

**Review by varshaprasad96 — APPROVED** [review]
/lgtm

**Comment by varshaprasad96** [comment]
@kkkkun The changes look good to me! Looks like the code-coverage is failing for not being able to publish the results. Have re-triggered the job to see what's happening.

**Pull request merged**
