### PR TITLE
:book: Book for v2

### PR DESCRIPTION
**Pull request by DirectXMan12**
This starts replacing the book for v2.  It switches to [mdbook](https://github.com/rust-lang-nursery/mdBook), which is like gitbook, but actually maintained (it's written for the Rust Programming Language Book and friends), with binary releases (no more "now `npm install` the entire universe), and a slightly more amenable plugin system (it's pretty easy to just call out to a built Go executable, which means we can do all sorts of fun stuff, such as including chunks of literate Go files, like from my previous attempt at this).

Try it out with `mdbook serve` from the `docs/book` subdirectory.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
cc @droot @mengqiy

**Comment by DirectXMan12** [comment]
This looks good for now.

Follow-ups: 

- [ ] fix all the TODO links
- [ ] reference docs
- [ ] restore the side-by-side sections (stretch)
- [ ] make sure the test project builds

**Comment by DirectXMan12** [comment]
whoops, typo -- one sec

**Comment by DirectXMan12** [comment]
typo all set

**Comment by nashasha1** [comment]
@DirectXMan12  hi, I saw http://book.kubebuilder.io has change to v2,  but v2 does not release yet. The https://v1.book.kubebuilder.io/ return 404. Could you fix this?

**Comment by DirectXMan12** [comment]
For posterity: we've fixed that link issue now

**Comment by DirectXMan12** [comment]
Sorry about that :-/

**Pull request merged**
