### PR TITLE
Fix domain resource issues in controller

### PR DESCRIPTION
**Pull request by fanzhangio**
- bind resource for controller based on whether resource is created.
  1) If resource is created in project, bind with created resource.
  2) If resource not created, gkv matches core types, bind with core-types.
  3) Else, using specified resourcePath by flag `--resource-pkg-path` (TODO)

#342 
#335 
#338

### CODE REVIEW

**Comment by DirectXMan12** [comment]
This presumably needs to be fixed controller-tools directly, not in the vendor directory.

**Comment by droot** [comment]
@fanzhangio the changes are on right track, but needs to be done in https://github.com/kubernetes-sigs/controller-tools first and then vendor'd in here.

**Comment by fanzhangio** [comment]
PR https://github.com/kubernetes-sigs/controller-tools/pull/54

This PR will be updated by dumping vendors if above PR merged.

**Comment by fanzhangio** [comment]
Done

**Pull request merged**
