### PR TITLE
:book: versioning update after the latest plugins definitions

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description**
Push @estroz's old suggestion in the VERSIONING.md file done in : https://github.com/kubernetes-sigs/kubebuilder/pull/1539
The@author of these changes is @estroz 

Closes: #1519

### CODE REVIEW

**Comment by estroz** [comment]
@camilamacedo86 I'll just rebase #1539, you can close this one.

**Comment by estroz** [comment]
Actually it looks like #1539 can't be re-opened after rebasing so lets merge this then I'll push followups.

/lgtm

**Comment by camilamacedo86** [comment]
rebased with master since got stuck to get merged. 
/lgtm

**Pull request merged**
