### PR TITLE
✨ (go/v4): Upgrade controller-tools from 0.11.3 to v0.12.0

### PR DESCRIPTION
**Pull request by kkkkun**
# Description  
Upgrade controller-tools to v0.12.0 for k8s 1.27.1
Part of https://github.com/kubernetes-sigs/kubebuilder/issues/3376

### CODE REVIEW

**Review by camilamacedo86 — COMMENTED** [review]
Hi @kkkkun, 

Thank you for your collaboration. Following some nits:

- 1 - Can you please rebase it with master branch?
- 2 - Then, could you please only upgrade controller-tools as described in the title and not ENVTEST (ENVTEST was bump already in the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/3383). 
- 3 - IMPORTANT: The changes should only be done for the go/v4 plugin. go/v3 is deprecated, and we should no longer touch on it. 
- 4 -  All PR titles require emojis to describe the kind of change, and then there are used to create the release notes. So, I hope that you do not mind, but I am updating it accordingly. Please, check the CONTRIBUTING.md guide for further information.

**Comment by kkkkun** [comment]
> Hi @kkkkun,
> 
> Thank you for your collaboration. Following some nits:
> 
> * 1 - Can you please rebase it with master branch?
> * 2 - Then, could you please only upgrade controller-tools as described in the title and not ENVTEST (ENVTEST was bump already in the PR: [✨ (go/v4): Upgrade binaries used for controller tests (ENVTEST_K8S_VERSION) from k8s version 1.26.1 to 1.27.1 #3383](https://github.com/kubernetes-sigs/kubebuilder/pull/3383)).
> * 3 - IMPORTANT: The changes should only be done for the go/v4 plugin. go/v3 is deprecated, and we should no longer touch on it.
> * 4 -  All PR titles require emojis to describe the kind of change, and then there are used to create the release notes. So, I hope that you do not mind, but I am updating it accordingly. Please, check the CONTRIBUTING.md guide for further information.
> * 5 - You must assign the CLA: [✨ (go/v4): Upgrade controller-tools from 0.11.3 to v0.12.0 #3388 (comment)](https://github.com/kubernetes-sigs/kubebuilder/pull/3388#issuecomment-1534131527)

1.  rebase done!
2.  only upgrade controller-tools to v0.12.0
3.  only change go/v4
4.  change done.
5.  done

Thanks all.

**Comment by kkkkun** [comment]
Part of `bump controller-tools for a version using the k8s 1.27` https://github.com/kubernetes-sigs/kubebuilder/issues/3376

**Review by camilamacedo86 — APPROVED** [review]
Great !! 🥇 

Thank you for your contribution

**Pull request merged**
