### PR TITLE
:book: add a note for bootstrapping webhooks for pods

### PR DESCRIPTION
**Pull request by mengqiy**
Put the note in an `<aside>` block.

fixes: #893

### CODE REVIEW

**Comment by DirectXMan12** [comment]
@DirectXMan12 offers help on styling it! :D

**Comment by DirectXMan12** [comment]
styling help provided :-)

**Comment by mengqiy** [comment]
Looks pretty good!
/lgtm

**Comment by jonnylangefeld** [comment]
Hmm I just stumbled over this trying to fix the bootstrapping problem, but would say that this explanation is pretty insufficient. It links to the kubernetes source, that shows me that I could use `objectSelector` in my webhook yaml. However the webhook yaml is generated with the `// +kubebuilder:webhook:` tag, and unfortunately there is [no `objectSelector` field available](https://github.com/kubernetes-sigs/controller-tools/blob/d9cb41e71febe368fa5d34b2e3a993e5a4fa4341/pkg/webhook/parser.go#L22) 😔 
So I'm still stuck with the bootstrapping problem.

**Comment by camilamacedo86** [comment]
Hi @jonnylangefeld, 

This PR was done a long time go and is merged already. could you please raise a new issue?

**Pull request merged**
