### PR TITLE
File interface

### LINKED ISSUE #1226: [Scaffold enhancement] File interface
# Context

## Current situation

The current `File` interface is as follows:

https://github.com/kubernetes-sigs/kubebuilder/blob/03f70fb1a0f7521f383a08e41562124021161baf/pkg/scaffold/input/input.go#L141-L145

The single method is not descriptive enough and does different tasks:
1. Sets default values
2. Returns a non-descriptive `Input` struct which contains:
    - Two fields needed to prepare the template: `Path` and `TemplateBody`
    - Several other fileds that are not used

Note: the `Input` struct also works as a parent class for mostly all `File`-implementing structs so that they can be injected some data from the scaffold. By mostly I mean all except the `PROJECT` file, which is an special-cased yaml file which doesn't have an embedded `Input`.

## `GetInput` usage

<details><summary>I have tracked <code>GetInput</code> usages.</summary>

### `pkg/scaffold/project.go`
Lines 101 and 106 for v1, 192 and 197 for v2:
https://github.com/kubernetes-sigs/kubebuilder/blob/03f70fb1a0f7521f383a08e41562124021161baf/pkg/scaffold/project.go#L101
https://github.com/kubernetes-sigs/kubebuilder/blob/03f70fb1a0f7521f383a08e41562124021161baf/pkg/scaffold/project.go#L106
https://github.com/kubernetes-sigs/kubebuilder/blob/03f70fb1a0f7521f383a08e41562124021161baf/pkg/scaffold/project.go#L192
https://github.com/kubernetes-sigs/kubebuilder/blob/03f70fb1a0f7521f383a08e41562124021161baf/pkg/scaffold/project.go#L197
The created variables are used in lines 113 and 127 for v1, and 204 and 218 for v2:
https://github.com/kubernetes-sigs/kubebuilder/blob/03f70fb1a0f7521f383a08e41562124021161baf/pkg/scaffold/project.go#L113
https://github.com/kubernetes-sigs/kubebuilder/blob/03f70fb1a0f7521f383a08e41562124021161baf/pkg/scaffold/project.go#L127
https://github.com/kubernetes-sigs/kubebuilder/blob/03f70fb1a0f7521f383a08e41562124021161baf/pkg/scaffold/project.go#L204
https://github.com/kubernetes-sigs/kubebuilder/blob/03f70fb1a0f7521f383a08e41562124021161baf/pkg/scaffold/project.go#L218

Only the path is needed. Setting the default values (which is also done by `GetInput`) is not needed here except for the path itself.

### `pkg/scaffold/scaffold.go`
Line 229:
https://github.com/kubernetes-sigs/kubebuilder/blob/03f70fb1a0f7521f383a08e41562124021161baf/pkg/scaffold/scaffold.go#L229
Which is later used in line 235 and 238:
https://github.com/kubernetes-sigs/kubebuilder/blob/03f70fb1a0f7521f383a08e41562124021161baf/pkg/scaffold/scaffold.go#L235
https://github.com/kubernetes-sigs/kubebuilder/blob/03f70fb1a0f7521f383a08e41562124021161baf/pkg/scaffold/scaffold.go#L238
The usage in `doTemplate` are in lines 278, 291 and 292:
https://github.com/kubernetes-sigs/kubebuilder/blob/03f70fb1a0f7521f383a08e41562124021161baf/pkg/scaffold/scaffold.go#L278
https://github.com/kubernetes-sigs/kubebuilder/blob/03f70fb1a0f7521f383a08e41562124021161baf/pkg/scaffold/scaffold.go#L291-L292

The path is needed in lines 235, 291 and 292. The template body is needed in line 278. The side-effect of setting the default values is important here as the files are used to execute the templates in line 284:
https://github.com/kubernetes-sigs/kubebuilder/blob/03f70fb1a0f7521f383a08e41562124021161baf/pkg/scaffold/scaffold.go#L284

### `pkg/scaffold/project/project_test.go`
Line 49:
https://github.com/kubernetes-sigs/kubebuilder/blob/03f70fb1a0f7521f383a08e41562124021161baf/pkg/scaffold/project/project_test.go#L48-L52
It is used to set the default values.</details>

# Proposal

A new interface is proposed:

```go
type File interface {
	GetPath() string
	GetTemplateBody() string
	SetDefaults() error
}
```

<details><summary>Method usage</summary>

- `GetPath` would be used in lines 113, 127, 204 and 218 of `pkg/scaffold/project.go` and in lines 235, 291 and 292 of `pkg/scaffold/scaffold.go`.
- `GetTemplateBody` would be used in line 278 of `pkg/scaffold/scaffold.go`.
- `SetDefaults` would be called before line 284 of `pkg/scaffold/scaffold.go` and in line 49 of `pkg/scaffold/project/project_test.go`.
- All the `GetInput` calls with their error handlings could be removed.</details>

This feature is part of a bigger change tracked in #1218

/kind feature

### PR DESCRIPTION
**Pull request by Adirio**
Closes #1226

### CODE REVIEW

**Comment by Adirio** [comment]
The Travis shouldn't relate to this PR but as it is just a draft I won't pay much attention for now.

**Comment by Adirio** [comment]
Retriggering Travis

**Comment by DirectXMan12** [comment]
@Adirio I kinda lost track of this.  What's the status?

**Comment by Adirio** [comment]
>What's the status?

Waiting for #1340 before implementing this.

**Comment by Adirio** [comment]
Waiting on #1359 
/hold

**Pull request closed without merging**
