### PR TITLE
✨ Update controller-tools version (v0.9.2->v0.10.0)

### PR DESCRIPTION
**Pull request by oscr**
Updates the go dependency sigs.k8s.io/controller-tools from v0.9.2- to v0.10.0

Part of #2908

### CODE REVIEW

**Comment by camilamacedo86** [comment]
Hi @oscr,

Thank you for the PR. We need to update it in the scaffolds and not only in the CLI, see:
- https://github.com/kubernetes-sigs/kubebuilder/blob/3bfc84ec8767fa760d1771ce7a0cb05a9a8f6286/pkg/plugins/golang/v3/scaffolds/init.go#L39

Also, we need to run make, generate and update the samples.

**Comment by oscr** [comment]
> * 0.9.2

Thank you @camilamacedo86! :pray: That's why I didn't get any generate diff.

**Review by camilamacedo86 — APPROVED** [review]
Great work 🥇

**Comment by everettraven** [comment]
Ah I see now that controller-tools will be updated as part of this PR. I was working on #2954 as part of updating the CLI go.mod to use k8s 1.25 dependencies and just pushed a controller-tools bump and a bump to the Go version in https://github.com/kubernetes-sigs/kubebuilder/blob/master/.github/workflows/unit-tests-legacy.yml

**Comment by oscr** [comment]
@everettraven That's awesome! Thank you so much for that :pray:

**Comment by everettraven** [comment]
@oscr #2954 is merged. This PR should just need a rebase.

**Comment by camilamacedo86** [comment]
Hi @oscr, just bump with the master to get https://github.com/kubernetes-sigs/kubebuilder/pull/2954 so that will pass and we can merge this one. 

c/c @everettraven

**Pull request merged**
