### PR TITLE
Add pwittrock to approvers

### PR DESCRIPTION
**Pull request by pwittrock**
Would like to be able to approve PRs such as this one: #1518

### CODE REVIEW

**Comment by pwittrock** [comment]
cc @droot @mengqiy @DirectXMan12

**Comment by DirectXMan12** [comment]
This seems fine to me.  Will give this a day just in case anyone has any follow-up comments, then merge.

/hold
/approve
/lgtm

**Comment by DirectXMan12** [comment]
(for reference, @pwittrock was moved to emeritus approvers after taking a break from the project for a bit)

**Comment by pwittrock** [comment]
Thanks @DirectXMan12!

**Pull request merged**
