### PR TITLE
:book: merge Chinese docs into the repo

### PR DESCRIPTION
**Pull request by majinghe**
#### Description

Merge Chinese docs(translated by China Cloud Native Community) into the repo, already discussed in the issue: https://github.com/kubernetes-sigs/kubebuilder/issues/1651.

### CODE REVIEW

**Comment by majinghe** [comment]
I signed it

**Comment by Adirio** [comment]
Several things about the PR you should fix before we can review it:
- Sign the CLA
- Use `:book:` or 📖 instead of `[doc]` as the PR title prefix
- Rebase
- Some of the changes you made re breaking the `Netlify` check, which actually generates the documentation as a preview. So your changes in the doc is breaking the doc gen utility.

**Comment by majinghe** [comment]
> Several things about the PR you should fix before we can review it:
> 
>     * Sign the CLA
> 
>     * Use `:book:` or 📖 instead of `[doc]` as the PR title prefix
> 
>     * Rebase
> 
>     * Some of the changes you made re breaking the `Netlify` check, which actually generates the documentation as a preview. So your changes in the doc is breaking the doc gen utility.

* I have signed the CLA, but the result is fail, i have asked help for [linux-foundation team](https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4/SUPPORT-3339?sda_source=notification-email)

* I have changed the PR title, now this item has passed the check.

* What do you means *Rebase*, to rebase the all commit to one commit or something also, it will appreciate if any detail info provided.

* Yes, team has changed the netlify to meet our Chinese docs's translate and deploy.

**Comment by Adirio** [comment]
> * What do you means _Rebase_, to rebase the all commit to one commit or something also, it will appreciate if any detail info provided.

No, thats called squashing commits. Your PR cant be merged because it has conflicts with some fields because it started from a quite old commit. You need to resolve those conflicts. GitHub lists the conflicts below the checks.

**Comment by majinghe** [comment]
Due to some other issue, close this PR.

**Pull request closed without merging**
