### PR TITLE
Revert "pkg/plugin/v3: use repo instead of directory basename as project name"

### PR DESCRIPTION
**Pull request by camilamacedo86**
Reverts kubernetes-sigs/kubebuilder#1596

Important: My goal is not to move forward with. just check if others are also ok with.

### CODE REVIEW

**Comment by camilamacedo86** [comment]
Hi @estroz, 

I LGTM the #1596 but shows that it needs more discussion. 
I'm sorry for the inconvenience, however, are you ok with we revert and raise its discussions again? 

c/c @estroz

**Comment by pwittrock** [comment]
@camilamacedo86 Lets hold this for discussion.

**Comment by estroz** [comment]
Closed by #1603 

/close

**Pull request closed without merging**
