### PR TITLE
 :seedling:Evaludate and Apply Latest Lint Rules and Features

### LINKED ISSUE #3847: Evaludate and Apply Latest Lint Rules and Features
### What do you want to happen?

It turns out there's a long history ever since `golangci-lint` [was introduced](https://github.com/kubernetes-sigs/kubebuilder/commit/887037d09add306a138f2935eedd9b30f06e5aa6).
I would suggest re-evaluating the usage of lint tools to ensure adherence to the best practices of Golang coding.

Suggestion:
1. Check [the config of `revive`](https://github.com/kubernetes-sigs/kubebuilder/blob/cc338d729c2a578ae491860e3eb71e63864b1390/.golangci.yml#L22-L58).
   1. Any options can be dropped?
   2. Any new features can be added?
   3. Why there are some *disabled*, it is necessary still?
1. Check the latest feature of `golangci-lint`
1. Update the code if necessary

### Extra Labels

/kind cleanup

### PR DESCRIPTION
**Pull request by prashantrewar**
Fixes #3847

### CODE REVIEW

**Review by camilamacedo86 — COMMENTED** [review]
HI @prashantrewar 

When we do changes in the scaffolds we must to run `make generate` so that all samples and docs will be properly updated. Can you please, rebase with master branch and ensure that you run the command to push a commit?


Also, please ensure that you squash the commits.
We should not have more than one commit for this PR.

**Comment by prashantrewar** [comment]
Hey @camilamacedo86, I made the changes. Please take a look.

Thank you for the guidance.

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

That is great 🥇 

Thank you a lot for your contribution

**Pull request merged**
