### PR TITLE
Issue #791 Use golangci-lint instead of go vet for generated project

### LINKED ISSUE #791: Use `golangci-lint` metalinter
[`golangci-lint`](https://github.com/golangci/golangci-lint) is a Go metalinter.
Kubebuilder generated project should use golangci-lint.

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Fixes #791 

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
Test failed with
```
make: golangci-lint: Command not found
make: *** [vet] Error 127
The command "GO111MODULE=on TRACE=1 ./test.sh" exited with 2.
```
Looking in to it

**Comment by LalatenduMohanty** [comment]
I see other instances of `vet` in the `docs` and `testdata` . Should I fix those as well?
```
$ git grep vet
docs/book/src/cronjob-tutorial/testdata/project/Makefile:test: generate fmt vet manifests
docs/book/src/cronjob-tutorial/testdata/project/Makefile:manager: generate fmt vet
docs/book/src/cronjob-tutorial/testdata/project/Makefile:run: generate fmt vet
docs/book/src/cronjob-tutorial/testdata/project/Makefile:# Run go vet against code
docs/book/src/cronjob-tutorial/testdata/project/Makefile:vet:
docs/book/src/cronjob-tutorial/testdata/project/Makefile:       go vet ./...
testdata/gopath/src/project/Makefile:test: generate fmt vet manifests
testdata/gopath/src/project/Makefile:manager: generate fmt vet
testdata/gopath/src/project/Makefile:run: generate fmt vet
testdata/gopath/src/project/Makefile:# Run go vet against code
testdata/gopath/src/project/Makefile:vet:
testdata/gopath/src/project/Makefile:   go vet ./pkg/... ./cmd/...
testdata/project-v2/Makefile:test: generate fmt vet manifests
testdata/project-v2/Makefile:manager: generate fmt vet
testdata/project-v2/Makefile:run: generate fmt vet
testdata/project-v2/Makefile:# Run go vet against code
testdata/project-v2/Makefile:vet:
testdata/project-v2/Makefile:   go vet ./...
```

**Comment by droot** [comment]
@LalatenduMohanty This change will require fixing the `lint errors` in the generated project first :). Thats where the travis tests are failing.

So I would suggest creating a separate PR that fixes the lint errors in scaffolded code and then rebasing this PR after the other PR is merged.

**Comment by LalatenduMohanty** [comment]
/assign @pmorie

> @LalatenduMohanty This change will require fixing the `lint errors` in the generated project first :). Thats where the travis tests are failing.
> 
> So I would suggest creating a separate PR that fixes the lint errors in scaffolded code and then rebasing this PR after the other PR is merged.

Thanks for the feedback, I will working on it. However I am not sure about https://github.com/kubernetes-sigs/kubebuilder/pull/805#issuecomment-503907952.  Can you please let me know your suggestion?

**Comment by droot** [comment]
> However I am not sure about #805 (comment).

files under `testdata/project-v2` will be updated when you run generate_golden.sh
files under `testdata/project` needs to be kept as is because they are for version 1
updating files under `cronjob-tutorial` is a bit tricky. We have to find a good way to update the doc project. But for now, we can leave it as is.

**Comment by LalatenduMohanty** [comment]
@droot Created https://github.com/kubernetes-sigs/kubebuilder/pull/830 to fix the lint issues along with updated golden files

**Comment by camilamacedo86** [comment]
HI @LalatenduMohanty, 

Could you please rebase this one?

**Pull request closed without merging**
