### PR TITLE
feat: add dockerignore file to the scaffold (V3 only)

### PR DESCRIPTION
**Pull request by camilamacedo86**
Closes: #1246

### CODE REVIEW

**Comment by camilamacedo86** [comment]
/hold

Are you ok @DirectXMan12 @estroz about add this one for V2 as well?

**Comment by DirectXMan12** [comment]
should this be part of #1498 ?

**Comment by DirectXMan12** [comment]
otherwise seems fine

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12, 

This was in doubt. If we should move forward with just for V3 and using plugins or not. Really tks. I will put it in /hold until we are able to have +1 plugin merged and we address it as a new bump plugin version.

**Comment by camilamacedo86** [comment]
/hold cancel
Applied for v3-alpha now.

**Pull request merged**
