### PR TITLE
 🐛 (makefile): make kustomize does not show curl error output

### PR DESCRIPTION
**Pull request by kilsilent**
## Description

(makefile): make kustomize does not show curl error output #2873

### CODE REVIEW

**Comment by everettraven** [comment]
Hi @kilsilent ! Thanks for the contribution! I think this is a useful change but before we can continue with this PR we need a couple things:
1. Before your PR can be accepted you will need to sign the CLA Authorization. I believe you may also need to sign your commits with the `-s` option when running `git commit`.
2. The PR title is very long and doesn't quite match the PR title standards. Would you mind changing the title of the PR to something more along the lines of: :bug: (makefile): `make kustomize` does not show error output

Once these are done, I would be happy to give it the ok-to-test label and work on getting this merged.

**Comment by kilsilent** [comment]
> Hi @kilsilent ! Thanks for the contribution! I think this is a useful change but before we can continue with this PR we need a couple things:
> 
> 1. Before your PR can be accepted you will need to sign the CLA Authorization. I believe you may also need to sign your commits with the `-s` option when running `git commit`.
> 2. The PR title is very long and doesn't quite match the PR title standards. Would you mind changing the title of the PR to something more along the lines of: 🐛 (makefile): `make kustomize` does not show `curl` error output
> 
> Once these are done, I would be happy to give it the ok-to-test label and work on getting this merged.

Thank you very much for your reply. I have completed the modification according to your suggestions

**Review by everettraven — APPROVED** [review]
These changes are pretty straightforward and makes sense to me! Thanks for the contribution @kilsilent !

**Comment by kilsilent** [comment]
Thanks




凯凯
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubernetes-sigs/kubebuilder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月26日(星期五) 晚上9:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubernetes-sigs/kubebuilder]  🐛 (makefile): make kustomize does not show curl error output (PR #2873)





 
@everettraven approved this pull request.
 
These changes are pretty straightforward and makes sense to me! Thanks for the contribution @kilsilent !

**Comment by kilsilent** [comment]
> These changes are pretty straightforward and makes sense to me! Thanks for the contribution @kilsilent !

thanks

**Review by camilamacedo86 — APPROVED** [review]
It shows ok for me either 👍 

Thank you for your contribution 🥇

**Comment by kilsilent** [comment]
> It shows ok for me either 👍
> 
> Thank you for your contribution 🥇

Many Thanks

**Pull request merged**
