### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description**
Fix CI - By updating go version in the images

**Motivation**
Closes: #1169

### CODE REVIEW

**Comment by Adirio** [comment]
Small nit: I think you wanted to say `Closes: #1169` not `Closes: #1168`.

**Comment by ncdc** [comment]
I would not recommending upgrading to go 1.13 until kubebuilder's dependencies have all upgraded to the versions of apimachinery, client-go, etc. that are built with go 1.13, which will be those coming from Kubernetes v1.17.

/hold

**Comment by Adirio** [comment]
The point is that 1.13 is already being used by an already merged PR, if I'm not mistaken.

**Comment by ncdc** [comment]
I see that #1135 upgraded kubebuilder to use go1.13. @DirectXMan12 don't you want to wait until the staging repos have been updated to use go1.13 as well (which means waiting for kube v1.17)?

**Comment by ncdc** [comment]
I'll remove my hold since I'm not an active kubebuilder contributor, but I would have thought this repo would have waited to upgrade to go1.13 until after a release of Kubernetes came out that is built with go1.13.

/hold cancel

**Comment by DirectXMan12** [comment]
> but I would have thought this repo would have waited to upgrade to go1.13 until after a release of Kubernetes came out that is built with go1.13

We were mainly holding till we could be sure that we wouldn't cause people too much of a headache with their dev environments -- code wise, things seem to work fine.  Kubernetes tends to move pretty slowly with these things because of its complicated build scripts & the way gengo works, and I'm not sure we also want to couple ourselves to that cadence.

If there are any active issues, please do mention them before the release.

@ncdc and @camilamacedo86 have already made me aware of https://github.com/kubernetes/kubernetes/issues/85103  already (the module solver fails w/o goproxy when people name branches after commit shas, which seems like a Bad Idea™ anyway)

**Pull request merged**
