### PR TITLE
🌱 added test for exec.go

### LINKED ISSUE #3211: Increase the test coverage with unit tests
### What do you want to happen?

By looking at the coveralls reports we can see that we have some implementations which could be better covered. We do not cover 100% of the code but would be great increase the coverage and ensure that we have no red and orange files/dirs, see: https://coveralls.io/github/kubernetes-sigs/kubebuilder?branch=master

Example: 

We could add more tests for cmd_helpers.go, completiton.go and version.go:

Screenshot 2023-02-08 at 14 17 13

### Extra Labels

_No response_

### PR DESCRIPTION
**Pull request by khareyash05**
added tests for exec.go
Fixes #3211

### CODE REVIEW

**Comment by khareyash05** [comment]
@camilamacedo86 All my tests are passed but still the workflow is failing. Kindly help.

**Comment by khareyash05** [comment]
@camilamacedo86 Kindly help me with the failing workflow. All my test cases have passed.

**Review by camilamacedo86 — COMMENTED** [review]
/ok-to-test
/lgtm
/approved

**Comment by camilamacedo86** [comment]
/approved cancel

@khareyash05 could you please squash the commits? otherwise, the logs/history does not end up well?

**Comment by khareyash05** [comment]
@camilamacedo86 Squashed commits

**Review by camilamacedo86 — APPROVED** [review]

**Pull request merged**
