### PR TITLE
Added explanatory note about the index

### LINKED ISSUE #1422: Kubebuilder book: Why create a custom metadata field "controller" in job instead of just ownerReferences
I was going through the tutorial in the book for Cronjobs. On [this page](https://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html#2-list-all-active-jobs-and-update-the-status) the concept of a `jobOwnerKey` field is introduced:

```golang
var (
    jobOwnerKey = ".metadata.controller"
```

I don't completely understand why we cannot just rely on the build-in ownerReferences type? Is this because it is not indexable by the cache FieldIndexer and we use the jobOwnerKey solely as an indexable id for it?

**Proposals if this is the case:**
- In the book documentation, explain the function of the jobOwnerKey (If you explain it here, I can also PR it)
- If lists of objects like ownerReferences are not indexable, perhaps start a proposal to make them so?

P.S: I didn't know we could add custom metadata to resources? I assume the jobOwnerKey is only used by the local cache then.

### PR DESCRIPTION
**Pull request by toonsevrin**
Resolves #1422. 

Please proof read this change, review it and compile it to html to verify it compiles correctly (I haven't checked this).

Feel free to make changes as you deem fit.

### CODE REVIEW

**Comment by toonsevrin** [comment]
CLA is now signed.

**Comment by Adirio** [comment]
A couple comments:
- Below this comments you can see a check called `netlify/kubebuilder/deploy-preview`. If you click in [`Details`](https://deploy-preview-1424--kubebuilder.netlify.com/) you can see the book updated.
- After this gets merged, a cherry pick will be needed in `book-v2` branch as this is not a new feature, but documenting an existing one. [Link](https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md#how-to-contribute-to-docs)

About the change itself, the style looks really poor in my opinion, could you give it another thought now that you have the link to see how it looks like. The text itself LGTM.

/ok-to-test

**Comment by toonsevrin** [comment]
@Adirio oh damn, that's most definitely not the style I was aiming for, I copied this code block from [another page](https://deploy-preview-1424--kubebuilder.netlify.com/cronjob-tutorial/running.html) where it worked just fine...

Let me investigate ;)

**Comment by toonsevrin** [comment]
@Adirio fixed the styling issue: I remembered these HTML-in-markdown parsers don't like indentation.

Anyways, feel free to merge :)

**Comment by Adirio** [comment]
> Just to be clear, I should create a new PR to book-v2 and close this one?

Intructions are as follows:

> If updating existing docs, the PR should target `master` branch and then cherry-picked into `book-v2` branch.

So this PR is ok. Not sure who is suposed to cherry pick this to `book-v2`. Can you throw some light here @mengqiy?

Related to the style, looks better now. Lets see what mantainers think about how it fits the rest of the book.

/lgtm

**Comment by toonsevrin** [comment]
Jokes on me thinking you wanted me to create a new PR (instead of simply merging the commits from master into book-v2)...

**Comment by Adirio** [comment]
> Jokes on me thinking you wanted me to create a new PR (instead of simply merging the commits from master into book-v2)...

We definetely don't want to merge `master` into `book-v2`, we just do that when a new release is out and thus all the book documentation that was for new features gets added to the book. What we want to do is a cherry-pick, that means applying the same commit to the other branch. I can help you with that in case it is your responsability (I'm still not sure about this, it may be owners responsability) when this gets merged if you need my help.

**Comment by toonsevrin** [comment]
> It shows fine :-)

Thanks, I just squashed them :)

**Comment by Adirio** [comment]
/lgtm

Reapplying

**Pull request merged**
