### PR TITLE
:sparkles: Upgrade the version of kubernetes to v1.18.0 for local e2e tests

### PR DESCRIPTION
**Pull request by prafull01**
Description:
Update the local tests e2e scripts to use the kubernetes version v1.18.0

Motivation:
We are adding the kubebuilder e2e tests pre submit jobs on the kubernetes v1.18.0 in [#19690](https://github.com/kubernetes/test-infra/pull/19690)

### CODE REVIEW

**Comment by Adirio** [comment]
Should we hold this until the mentioned PR gets merged first so that we update the continous integration before the manual tests?

**Comment by Adirio** [comment]
Hold until the related PR gets merged

/lgtm
/hold

**Comment by prafull01** [comment]
This can be merged now as the PR on the infra side is merged

**Comment by camilamacedo86** [comment]
/hold cancel
/approve

👍

**Pull request merged**
