### PR TITLE
:book: improve plugin available doc (nits)

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description**
The work to provide the docs was split.
This PR just try to shape/improve what was added

### CODE REVIEW

**Comment by camilamacedo86** [comment]
@AlmogBaku @Ashwin901 could you please give a hand on this one? 
WDYT? Could we get it merged?

**Comment by Ashwin901** [comment]
I think it looks good @camilamacedo86

**Review by AlmogBaku — APPROVED** [review]

**Pull request merged**
