### PR TITLE
:sparkles: (go/v4) allow golangci-lint version into the Makefile to be customizable

### PR DESCRIPTION
**Pull request by redhatrises**
# Description

Create a variable to make clear the version used in the target.
Also, to allow  golangci-lint version to be customizable

### CODE REVIEW

**Review by camilamacedo86 — APPROVED** [review]
/lgtm
/approve

**Review by camilamacedo86 — CHANGES_REQUESTED** [review]
@redhatrises 

Thank you for your contribution 🥇 
Can you please revert the changes into `[pkg/plugins/common/kustomize/v2/scaffolds/webhook.go](https://github.com/kubernetes-sigs/kubebuilder/pull/3642/files#diff-efe5fb949909ea3705dd42c50f0fa08b85316bd316a0820c92c9e6680ef6aec1)` which has no relation with your PR?

See that it needs to pass in the CI to allow us to get it merged. 
For we allow it to move forward are required to

a) Rebase your branch with master
b) Run `make generate` -> So that all samples will be updated accordinly
c) Run `make lint-check` to check the issues (a few of them is possible to solve with make lint-fix automatically)
d) Squash the commits if you have more than one

**Comment by redhatrises** [comment]
> @redhatrises
> 
> Thank you for your contribution 🥇 Can you please revert the changes into `[pkg/plugins/common/kustomize/v2/scaffolds/webhook.go](https://github.com/kubernetes-sigs/kubebuilder/pull/3642/files#diff-efe5fb949909ea3705dd42c50f0fa08b85316bd316a0820c92c9e6680ef6aec1)` which has no relation with your PR?
> 
> See that it needs to pass in the CI to allow us to get it merged. For we allow it to move forward are required to
> 
> a) Rebase your branch with master b) Run `make generate` -> So that all samples will be updated accordinly c) Run `make lint-check` to check the issues (a few of them is possible to solve with make lint-fix automatically) d) Squash the commits if you have more than one

@camilamacedo86 thanks! I rebased, fixed the linting issue, and re-ran `make generate`... seems previous changes were made to the testdata that were missed.

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Pull request merged**
