### PR TITLE
use alias `batchv1` for package tutorial.kubebuilder.io/project/api/v1 throughout the tutorial project

### PR DESCRIPTION
**Pull request by ziyi-yan**
The `kubebuilder create api ...` generated code is using alias `batchv1` for package tutorial.kubebuilder.io/project/api/v1." in [`main.go`][1] and [`controllers/cronjob_controller.go`][2], instead of `batch`.
I'm not sure which one in is best practice. IMHO, it might be easier for newcomers to copy & paste the code from the tutorial page to make the demo works if we can use the same alias for the package throughout the tutorial.

[1]: https://github.com/ziyi-yan/kubebuilder-tutorial-cronjob/commit/b13eea79cc11c8fd6f05de3559351894207aae0d#diff-41ffe9f6f2df716e9790613297d33fd8R25
[2]: https://github.com/ziyi-yan/kubebuilder-tutorial-cronjob/commit/b13eea79cc11c8fd6f05de3559351894207aae0d#diff-7ddfb3e035b42cd70649cc33393fe32cR27

### CODE REVIEW

**Comment by DirectXMan12** [comment]
Please provide a description, as well as a justification for this PR.

For reference: using `batchv1` makes updating the API version in use require many more mechanical changes, so I don't recommend using that pattern (it's also a lot to type on longer api versions).

**Comment by DirectXMan12** [comment]
/hold

I'm tempted to close this outright, but I'll wait till the submitter responds.

**Comment by ziyi-yan** [comment]
@DirectXMan12 Thanks for your advice. I have edited the description, PTAL.

**Comment by ziyi-yan** [comment]
@DirectXMan12 I found out that [this line of code][1] is just using a kind of long alias `batchv1beta1 ` as you said but it conforms to the same convention for package aliases like `batchv1` and `kbatchv1`. It could be justification for the other issue #896, too.

[1]: https://github.com/ziyi-yan/kubebuilder/blob/dbed15f4cbba7104a2cc8e2c8ec9258c56ff16b5/docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_types.go#L20

**Comment by camilamacedo86** [comment]
HI @ziyi-yan, 

If you still thinking that this PR should be merged, could you please rebase it with the master branch? 
Also, if not could you please close this one.

**Pull request closed without merging**
