### PR TITLE
 :sparkles: upgrade k8s deps from 1.24 to 1.24.2, controller-tools from v0.9.0 to v0.9.2 and controller-runtime from v0.12.1 to v0.12.2

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Description

- upgrade k8s deps from 1.24 to 1.24.2
- controller-tools from v0.9.0 to v0.9.2 
- controller-runtime from v0.12.1 to v0.12.2

### CODE REVIEW

**Comment by camilamacedo86** [comment]
Note in this case is expected the PR fails in the APIDiff / Verify API differences (pull_request).
We will skip this one to move forward. This check is done only to help us not introduce breaking changes.

**Review by everettraven — APPROVED** [review]
LGTM. This should be good to go after resolving the problems in the Prow tests

**Pull request merged**
