### PR TITLE
:book: - Update makefile-helpers.md

### PR DESCRIPTION
**Pull request by noquarteer**
Added documentation discussed in #1693

### CODE REVIEW

**Comment by noquarteer** [comment]
I signed it

**Comment by noquarteer** [comment]
I signed it

**Review by camilamacedo86 — APPROVED** [review]
Tks for the contribution. 
It is fine for me. 

/approve

**Comment by camilamacedo86** [comment]
Hi @noquarteer,  

for we are able to move forward with you need to follow up the instruction in https://github.com/kubernetes-sigs/kubebuilder/pull/1695#issuecomment-699022660. Could you please check this one?

**Comment by noquarteer** [comment]
Hi @camilamacedo86! I already signed and the flag  `cncf-cla: no` was removed. It seems like some Jobs failed.

**Comment by camilamacedo86** [comment]
Hi @noquarteer, 

It is fine. Sometimes the jobs have flakes than we just re-trigger the specific one that fails with the comment.

**Review by gabbifish — APPROVED** [review]
/approve

**Pull request merged**
