### PR TITLE
Cherry-pick envtest example

### PR DESCRIPTION
**Pull request by gabbifish**
This PR cherry-picks the new envtest documentation for the cronjob example.

### CODE REVIEW

**Comment by gabbifish** [comment]
@camilamacedo86 would love your review on this! :)

**Comment by camilamacedo86** [comment]
hi @gabbifish,

It is not passing in the tests. See that it is failing the test to check if the testdata was generated. The testdata is updated with the command `make generate`. More info: [CONTRIBUTING.md](https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md)

However, I do not think that is required to do the cherry-pick the docs will be updated in the next release. But if you wish to check it in the book now then, to make the cherry-pick is required to do the fixes to allow it pass. E.g https://github.com/kubernetes-sigs/kubebuilder/pull/1554/files

**Comment by gabbifish** [comment]
@camilamacedo86 Hey there! Yeah, I'm trying to figure out the tricky `sigs.k8s.io/kubebuilder-declarative-pattern` dependency issue right now :( I'll try to fix it. I'm just excited to see my docs live on the kubebuilder book! :)

**Comment by gabbifish** [comment]
@camilamacedo86 The tests are passing--I think this should be ready for review/merge! :)

**Comment by camilamacedo86** [comment]
hi @gabbifish, 

I think we need to first to push a fix to the master. See the preview: 

Screenshot 2020-07-08 at 10 10 56

 
then, we can cherry-pick the doc update + bug fix.

**Comment by camilamacedo86** [comment]
Hi @gabbifish, 

See that your change broke the docs. We need to fix it in the master as soon as possible. Could you please check that?
To verify the docs we use the preview. You can see more info in the CONTRIBUTION.md doc as well. 

See that in the master we have: https://book.kubebuilder.io/reference/writing-tests.html
And then, after your changes the page is blank: https://deploy-preview-1579--kubebuilder.netlify.app/reference/writing-tests.html

**Comment by camilamacedo86** [comment]
Hi @gabbifish, 

Could you check my above comment? Wdyt about addressing the fix for the docs in master first?  Are you able to help with? Do you think that we need to track an issue to fix the docs?

**Comment by gabbifish** [comment]
Hi @camilamacedo86! I went back to try and find the docs rendering errors I might have introduced, but it looks like https://deploy-preview-1579--kubebuilder.netlify.app/cronjob-tutorial/writing-tests.html looks correct now--did the fix from master get cherry-picked into this branch already?

Please let me know if there are still issues!

**Comment by camilamacedo86** [comment]
Hi @gabbifish, 

I think that I found the root cause issue.  See: 
 
- https://deploy-preview-1579--kubebuilder.netlify.app/cronjob-tutorial/writing-tests.html
- https://deploy-preview-1579--kubebuilder.netlify.app/reference/writing-tests.html

In the PR shows that a new sub-menu was created when I understand that we should use the pre-existence one : See:

It should be in the references (writing controller test): 
Screenshot 2020-07-31 at 10 32 48

When it is in the tutorial (writing tests):
Screenshot 2020-07-31 at 10 32 40

I think the fix that needs to be done in the master and then cherrry-picked to here  👍

**Comment by gabbifish** [comment]
Cherry-picked the fix from master to this branch! Let me know how things look--I checked that the links to https://deploy-preview-1579--kubebuilder.netlify.app/reference/envtest.html worked from both the sidebar (4.8, Configuring EnvTest) and the link at the top of https://deploy-preview-1579--kubebuilder.netlify.app/cronjob-tutorial/writing-tests.html :D

**Comment by gabbifish** [comment]
Oop, looks like i need to rebase on this branch again to fix travis CI (I see some dependency issues)

**Comment by gabbifish** [comment]
cc @camilamacedo86 this should pass now, but I ran into some weird dependency problems along the way--even though this PR does nothing to change the dependencies in the root `testdata/` directory, running `make check-testdata` still required me to apply and add changes to `testdata/project-v2-addon/go.mod`? Perhaps we shouldn't even be running `make check-testdata` on the book-v2 branch because its source of truth is whatever is in the master branch...

**Comment by camilamacedo86** [comment]
HI @gabbifish, 

Note that the common process is just performed merges here when we do the release and all from the master will be bumped here.  However, we also can cherry-pick something from the master but in some scenarios, it might need some adjustments as you did. It is ok for now. 

However, if we decide to change how things work then, I think ideally we need to raise our suggestions and make a proposal. Maybe this kind of discussion can be started in an issue and etc..

**Comment by camilamacedo86** [comment]
It is just a cherry-picks for docs. 
PR #1521 which adds the example was checked for my contributors and maintainers. 
The second pr #1521 was just to fix the layout of the doc and was checked by me and @pwittrock.

So, it shows fine and required to go alive since many users have been asking for further info over how to test their controllers. 
Great contribution @gabbifish 🥇 

/lgtm
/approve

**Pull request merged**
