### PR TITLE
📖 (doc): Add "Kubebuilder Project Roadmap 2025"

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Add "Kubebuilder Project Roadmap 2025" Document**

This PR introduces the **Kubebuilder Project Roadmap 2025** as a standalone document under the `roadmaps` directory. It outlines key priorities and goals for the Kubebuilder project in 2025, focusing on stability, usability, and alignment with best practices.

### Purpose
The roadmap serves as a transparent guide for contributors, maintainers, and users, offering a clear vision of the project's direction and priorities for 2025. It aims to enhance collaboration and keep the Kubebuilder community aligned with the evolving Kubernetes ecosystem.

### Highlights:
- Improve webhook functionality, including CA injection, multiple webhook scaffolding, and end-to-end testing for conversion processes.
- Update tutorials to reflect the standards introduced by the DeployImage plugin, emphasizing best practices.
- Propose a system to notify users of updates and simplify the upgrade process with automation tools.

This document is a work-in-progress and will evolve based on community input and project needs.

### CODE REVIEW

**Comment by camilamacedo86** [comment]
/hold

To seek feedback and allow the community give their inputs

**Comment by chinglinwen** [comment]
I've got two things to note, hope it can be considered

## CRD in Go code
I'd like  to have crd write in go, and create crd when main.go runs, similar to this approach: https://github1s.com/k3s-io/helm-controller/blob/master/pkg/crd/crds.go


```go
package crd

import (
	v1 "github.com/k3s-io/helm-controller/pkg/apis/helm.cattle.io/v1"
	"github.com/rancher/wrangler/v3/pkg/crd"
)

func List() []crd.CRD {
	chart := crd.NamespacedType("HelmChart.helm.cattle.io/v1").
		WithSchemaFromStruct(v1.HelmChart{}).
		WithColumn("Job", ".status.jobName").
		WithColumn("Chart", ".spec.chart").
		WithColumn("TargetNamespace", ".spec.targetNamespace").
		WithColumn("Version", ".spec.version").
		WithColumn("Repo", ".spec.repo").
		WithColumn("HelmVersion", ".spec.helmVersion").
		WithColumn("Bootstrap", ".spec.bootstrap").
		WithStatus()

	config := crd.NamespacedType("HelmChartConfig.helm.cattle.io/v1").
		WithSchemaFromStruct(v1.HelmChartConfig{})

	return []crd.CRD{chart, config}
}
```

https://github1s.com/k3s-io/helm-controller/blob/master/main.go#L60-L61
```go
	ctx := cmd.Context()
	if err := wcrd.Create(ctx, clientConfig, crd.List()); err != nil {
		return err
	}
```

https://pkg.go.dev/github.com/rancher/wrangler/v3/pkg/crd

https://github.com/rancher/wrangler/blob/v3.1.0/pkg/crd/print.go#L57-L64
```go
func Create(ctx context.Context, cfg *rest.Config, crds []CRD) error {
	factory, err := NewFactoryFromClient(cfg)
	if err != nil {
		return err
	}

	return factory.BatchCreateCRDs(ctx, crds...).BatchWait()
}
```
> this way, it can be a lot simpler with a single deployment resource to apply.

> would like kubebuilder to scaffold to generate such go file, and glue by main.go
> say a file sit aside with types.go, maybe name: ${types}_crd_generated.go

## Customize Subresource helper
another area is how kubebuilder can help on customize subresource part
- similar to kubevirt, it handle certain operation in subresource manner.

**Comment by camilamacedo86** [comment]
Hi @chinglinwen 

About https://github.com/kubernetes-sigs/kubebuilder/pull/4316#issuecomment-2498148441, could you please raise an issue about it so that we can start to look and see the following steps forward?

**Review by mateusoliveira43 — APPROVED** [review]

**Comment by camilamacedo86** [comment]
I am moving forward with this one since no objections have been raised and we are close to 2025 now.
Anyway, this is a live doc, and we can change it anytime we see that it is required.

**Pull request merged**
