### PR TITLE
fix bug when run "kubebuilder create api --group apps --version v1"

### PR DESCRIPTION
**Pull request by answer1991**
this PR will fix the bug #516

### CODE REVIEW

**Comment by answer1991** [comment]
@pwittrock

**Comment by droot** [comment]
@answer1991 We need a way better (and scalable) way to resolve the conflicts in import paths when the user resources conflicts with the core resources. This PR addresses just for the Deployments resource. For your use-case, a possible workaround would be to use `--example false` in the create command.

**Comment by answer1991** [comment]
@droot hi,

Yes, you are right. I was creating apis with “--group apps --version v1” and fix this issue in the most directly way. 

If you have any other plan to fix this issue, please feel free to close my PR.

Otherwise, I would like to continue to work on this issue and enhance my PR.

**Comment by droot** [comment]
@answer1991 

>If you have any other plan to fix this issue, please feel free to close my PR.

Not currently. So for now, you can improve this PR. Pl. note tests are not passing on this PR currently. Check the travis failures.

**Pull request closed without merging**
