### PR TITLE
:sparkles: (API) deprecate kustomize/v1 and go/v3 packages

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Description

deprecate kustomize/v1 and go/v3 packages 

## Motivation

https://github.com/kubernetes-sigs/kubebuilder/issues/3117
https://github.com/kubernetes-sigs/kubebuilder/discussions/3217

### CODE REVIEW

**Review by Kavinjsir — COMMENTED** [review]
If we are going to deprecated `golang/v3`, should we bump the cmd default plugin to `gov4bundle`?

**Comment by camilamacedo86** [comment]
Hi @Kavinjsir,

> If we are going to deprecated golang/v3, should we bump the cmd default plugin to gov4bundle? 
The go/v3 is deprecated already on master
Here we are deprecating the API
Also, we have another PR to just make go/v4 the default one, see; https://github.com/kubernetes-sigs/kubebuilder/pull/3278

**Comment by Kavinjsir** [comment]
> 

Yeah, I noticed that later. That makes sense!

**Review by Kavinjsir — APPROVED** [review]

**Pull request merged**
