### PR TITLE
:warning: remove component config since it is no longer supported by controller-runtime and is deprecated

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description**

The ComponentConfig has been deprecated in the Controller-Runtime since its version 0.15.0.  [More info](https://github.com/kubernetes-sigs/controller-runtime/issues/895)
Moreover, it has undergone breaking changes and is no longer functioning as intended.
As a result, Kubebuilder, which heavily relies on the Controller Runtime, has also deprecated this feature,
no longer guaranteeing its functionality from version 3.11.0 onwards. You can find additional details on this issue [here](https://github.com/kubernetes-sigs/controller-runtime/issues/2370

More info: https://github.com/kubernetes-sigs/kubebuilder/discussions/3469

### CODE REVIEW

**Comment by camilamacedo86** [comment]
/hold

To allow reviews

**Review by varshaprasad96 — APPROVED** [review]
Thanks for the PR, @camilamacedo86!

I did a quick search for `ComponentConfig` locally from your branch, and looks like this PR removes it all :))

/lgtm
/approve

**Comment by camilamacedo86** [comment]
I will wait up next week for we get those merged

**Pull request merged**
