### PR TITLE
helpfully show progress of kubebuilder download

### PR DESCRIPTION
**Pull request by drnic**
It isn't obvious that the download is 60+Mb and may take some time on slow internet. Progress bars FTW.

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    69  100    69    0     0    315      0 --:--:-- --:--:-- --:--:--   315
100   125  100   125    0     0    480      0 --:--:-- --:--:-- --:--:--   480
100   628    0   628    0     0    853      0 --:--:-- --:--:-- --:--:--  613k
100 60.6M  100 60.6M    0     0   563k      0  0:01:50  0:01:50 --:--:--  955k
```

### CODE REVIEW

**Comment by camilamacedo86** [comment]
/ok-to-test

It cannot be merged yet. See that is not passing in the CI. Following the error. 

> Please make sure you have run ./generate_golden.sh if you have changed the scaffolding
> The command "./golden_test.sh" exited with 1.

Shows that are missing updated the golden_test. To solve it I'd like to suggest rebase with master and run `make generate`. 

c/c @DirectXMan12

**Comment by drnic** [comment]
@camilamacedo86 sorry, I submitted the PR via github. I'll clone it and run the command soon.

**Comment by camilamacedo86** [comment]
Hi @drnic, 

It is too small, I know. But I think the bot will not able to merge without it pass in the CI anyway.

**Comment by drnic** [comment]
Not related to the PR, but the process for submitting tiny fix seems large compared to the fix.

```
git clone https://github.com/kubernetes-sigs/kubebuilder
cd kubebuilder
hub fork
gco -b patch-1
git pull drnic patch-1
./golden_test.sh
```
But then I get a go error
```
Current directory is not in $GOPATH
```
Which is confusing since the repo has Go Modules `go.mod/sum`.

I move my new repo into `$GOPATH/src/sigs.k8s.io/kubebuilder` and run `./golden_test.sh` but it fails:

```
+ popd
~/Projects/gopath/src/sigs.k8s.io/kubebuilder
git status testdata --porcelain
 M testdata/project-v2/Makefile
git diff testdata
Golden test failed!
Please make sure you have run ./generate_golden.sh if you have changed the scaffolding
```

I don't think I "changed the scaffolding", but I run `./generate_golden.sh` as suggested and it passes.

Somewhere the `testdata/project-v2/Makefile` file has been modified:
```diff
 generate: controller-gen
-       $(CONTROLLER_GEN) object:headerFile=./hack/boilerplate.go.txt paths="./..."
+       $(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."
```
I add this to my commit with `gca --amend`.

Now `./golden_test.sh` passes.

Apparently `testdata/project-v2/Makefile` changed. Oh well, hopefully it's just a one time oddity for me.

**Comment by camilamacedo86** [comment]
Hi @drnic, 

Actually, you do not need to do all these steps. You can use the command `make generate`. Note that the gen files have some tricks over controller-gen version used and using the make target make the things easier. 

Also, if you have time give a look in the [CONTRIBUTING](https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md). There you can find some valid/helpful info as well.

**Comment by Adirio** [comment]
> Not related to the PR, but the process for submitting tiny fix seems large compared to the fix.

Tiny fixes can be PR as you did while they do not change the result in testdata (this also includes changing things in the rest of the directories that would mean that testdata is changed when the golden test is executed). Your PR doesn't change testdata so it could be submited as you did. More info on why ii was failing below.

> Apparently `testdata/project-v2/Makefile` changed. Oh well, hopefully it's just a one time oddity for me.

#1016 PR got merged recently. It didn't regenerate the testdata directory when it should. As it was a quite old PR, maybe the repository wasn't configured to run Travis when it was submitted or something like that, so the bug was introduced. That means that any PR now will fail the Travis check.

I made a hotfix (#1288) yesterday but wasn't merged yet, which does exactly the same you mention here. It is a separate PR for the hotfix to keep things organized. Once it gets merged any other PR will start passing again. If the hotfix gets merged first, I think this PR may need a rebase (which would basically remove the fix as it was already commited) in order for git to be able to merge this afterwards. You could also remove the fix and wait for the hotfix to get merged, and re-trigger Travis afterwards (closing and opening the PR does the trick to re-trigger Travis).

**Pull request merged**
