### PR TITLE
:book: Fix cronjob tutorial to delete and get next schedule correctly

### PR DESCRIPTION
**Pull request by khchan123**
- Support default parameter field
- Fix wrong deletion on SuccessfulJobsHistoryLimit & FailedJobsHistoryLimit
- Fix wrong next schedule as returned lastMissed is a pointer
- Delete dependent Job in background when deleting CronJob

### CODE REVIEW

**Comment by khchan123** [comment]
I signed it

**Comment by DirectXMan12** [comment]
Can we just move the defaulting to the defaulting webhook, please?

**Comment by DirectXMan12** [comment]
otherwise seems reasonable

**Comment by khchan123** [comment]
I overlooked and figured out the defaulting code already on webhook. Removed that part in the new version.

**Pull request merged**
