### PR TITLE
🌱  Adds version command E2E test to improve coverage

### PR DESCRIPTION
**Pull request by sklarsa**
My first PR for this project, so I went for a bite-sized one.  This PR adds a small test that `Execute`s the `version` command to improve unit test code coverage from [this issue](https://github.com/kubernetes-sigs/kubebuilder/issues/3211).

### CODE REVIEW

**Review by camilamacedo86 — COMMENTED** [review]
/ok-to-test

**Comment by sklarsa** [comment]
@camilamacedo86 I just merged master to hopefully fix the tests...

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Pull request merged**
