### PR TITLE
📖: allow running cronjob tutorial w/o webhoooks

### PR DESCRIPTION
**Pull request by sayaoailun**
The code in the master branch disables env ENABLE_WEBHOOKS, so I made this bugfix.

Signed-off-by: sayaoailun <guojianwei007@126.com>

### CODE REVIEW

**Comment by camilamacedo86** [comment]
Hi @sayaoailun, 

Could you please update the title with the correct mojo? It is ought to be :book:.

**Comment by sayaoailun** [comment]
> 
> 
> Hi @sayaoailun,
> 
> Could you please update the title with the correct mojo? It is ought to be 📖.

@camilamacedo86 done

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Pull request merged**
