### PR TITLE
:book: merge Chinese docs into the repo

### PR DESCRIPTION
**Pull request by majinghe**
#### Description

Merge Chinese docs(translated by China Cloud Native Community) into the repo, already discussed in the issue: https://github.com/kubernetes-sigs/kubebuilder/issues/1651.

### CODE REVIEW

**Comment by Adirio** [comment]
@DirectXMan12 would you mind updating the `book-v2-zh` branch tp `book-v2`?

**Comment by camilamacedo86** [comment]
Hi @majinghe, 

Really thank you for your collab. However, shows that it is missing a few nits to get merged as follows. 

1 - It shows not aligned with the master branch. We no longer use Travis for a while. So, I'd like to ask for you rebase this branch with master and do the required updates. 
2 - We need to check the doc changes in the preview. The netfly preview shows not working here as well. It might be solved with the master rebase. 

Hi @Adirio, 

After we get it merged we can check the branch name and etc. However, I do not think that we would need to have so far a v2 and V3 Chinese docs. We can move forward here by ensuring that we have the master docs in Chinese only for the latest version.

**Comment by zhangguanzhang** [comment]
any update?

**Comment by majinghe** [comment]
@camilamacedo86 @zhangguanzhang  Sorry to reply so late, will handle ASAP, really a little busy recently.

**Comment by majinghe** [comment]
@camilamacedo86  @zhangguanzhang  sorry to reply so late.  After rebase to main branch, a lot of contents needs to be translated again(this will take some time, will lead to the zh branch fall behind main branch again), i think this is the key point that how to keep the synchronization between zh branch and main branch.  Do you have any good way to fix such asynchronization?

My suggestion is that  treat Our community repo : https://github.com/cloudnativeto/kubebuilder as the Chinese docs repo, publish url is https://cloudnative.to/kubebuilder/ . Our community will translate the main branch to chinese regularly(for example 3 times a year).

This is just my question, any good idea from your guys side?

**Comment by camilamacedo86** [comment]
HI @majinghe, 

> ch. Do you have any good way to fix such synchronization?
Dealing with conflicts is not something nice, however, I usually use the merge tools for that which allow us to solve easier.

**Comment by Adirio** [comment]
If they are going to be only a couple translations per year, I would suggest translating the docs of releases instead of master.

**Comment by majinghe** [comment]
@camilamacedo86  I tried to fix the conflict and translate new content caused by rebae action. It really a lot of  workload, same to translate the whole content again. I think the same issue will be occur in the feature, it is really about the synchronization keeping for english master to  zh master. I agreed to the suggestion from @Adirio . Our Cloud Native  Community  translate the  kubebuilder to Chinese based on release instead of master.  How do you think about  this?

**Comment by camilamacedo86** [comment]
Hi @majinghe, 

We are near to release 3.0.0 stable. Would you like that us re-create this branch for the Chinese docs based in the latest version you are able to work on?

My main probably to get this merged is that we are unable to indeed check the docs preview. So, I think that brokes something regarding the docs.

**Comment by Adirio** [comment]
I think we need to define a bit better how do we want i18n to be handled in k9r. I added it to today's agenda as there seems not to be too many topics.

**Pull request closed without merging**
