### PR TITLE
rebase on k8s 1.10.1

### PR DESCRIPTION
**Pull request by mengqiy**

### CODE REVIEW

**Comment by mengqiy** [comment]
I thought we have travis CI for at least unit test since I saw trivis config file.
But I'm quite surprised we don't have any test for PR!

**Comment by pwittrock** [comment]
@mengqiy Yes, travis was just recently enabled for this repo.

@droot are you still working on getting travis setup?

**Comment by droot** [comment]
@mengqiy @pwittrock Yes, I am still working on the travis setup. hope to get it working today. @mengqiy Can you run all the tests locally for this PR ?

**Comment by droot** [comment]
@mengqiy We need to update thirdparty tools for k8s1.10 as well and make them available as docker image.

**Comment by pwittrock** [comment]
@mengqiy @droot I kicked the tires and this seems to work.  I pushed gcr.io/kubebuilder/thirdparty-linux:1.10 and gcr.io/kubebuilder/thirdparty-darwin:1.10 and tested it against the 1.10 tools.

**Comment by pwittrock** [comment]
SGTM

**Pull request merged**
