### PR TITLE
:running: structure and expose cobra cmds

### PR DESCRIPTION
**Pull request by hasbro17**
**Description:**
This restructures the cmd directory into pkgs that follows the
hierarchy of CLI subcommands. This helps to expose the `New***Command()` functions
that return the cobra subcommands so they can be consumed by downstream
projects that need to reuse Kubebuilder CLI for scaffolding projects.

The new pkg layout for cmd:
```console
cmd
├── alpha
│   ├── alpha.go
│   └── webhookv1
│       └── webhook_v1.go
├── create
│   ├── api
│   │   └── api.go
│   ├── create.go
│   └── webhookv2
│       └── webhook_v2.go
├── init
│   ├── go_version_test.go
│   └── init_project.go
├── main.go
├── update
│   └── vendor_update.go
├── util
│   ├── stdin.go
│   └── util.go
└── version
    └── version.go
```

**Motivation:**
This follows up on the [proposal](https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/integrating-kubebuilder-and-osdk.md) to integrate the Operator SDK with Kubebuilder.
The goal here is to expose the cobra commands for `kubebuilder init` and `kubebuilder create` so that the SDK can consume them downstream in its own CLI.
This allow the SDK to easily reuse Kubebuilder's scaffolding and CLI workflow.

While the plugins-based-extensions approach would still be a long term goal, consuming the Kubebuilder CLI in the SDK in the short run allows us to prototype and make changes in the SDK to make it compatible with Kubebuilder's project layout and expected workflow.

### CODE REVIEW

**Comment by hasbro17** [comment]
While this does expose all the cobra subcommands functions, the ones strictly needed for our purposes are the `NewCreateCmd()` and `NewInitProjectCmd()`, but since the other subcommands are no longer in pkg `main` they need to be exposed so they can be imported by their parent commands. 
We can move the other subcommand pkgs to `cmd/internal/...` if needed however.

Also since this effectively exposes a public API in Kubebuilder, #1042 would eventually need a fix to allow importing this as `sigs.k8s.io/kubebuilder/v2` or `sigs.k8s.io/kubebuilder/v3`. Although this can still be worked around by pinning to the commit so probably not that pressing.

**Comment by DirectXMan12** [comment]
o_O I was under the impression that OperatorSDK wouldn't being doing a separate CLI like this (hence the plugin stuff)?

/hold

**Comment by DirectXMan12** [comment]
@joelanford

**Comment by DirectXMan12** [comment]
> While the plugins-based-extensions approach would still be a long term goal, consuming the Kubebuilder CLI in the SDK in the short run allows us to prototype and make changes in the SDK to make it compatible with Kubebuilder's project layout and expected workflow.

This makes me inherently nervous, since it means that things are depending on the internals, more or less.  Can we chat about this next week at the meeting?  I was imagining prototyping would be done via "fork & custom plugin" or something similar, and then any changes to the plugin subsystem would be resubmitted.

**Comment by joelanford** [comment]
@DirectXMan12 Sorry, we didn't mean to catch you off guard with this. Let's chat more at the community meeting next week. We can talk through our thought process and discuss if there are any other alternatives.

**Comment by hasbro17** [comment]
Closing this per our offline discussion to explore a different strategy of reusing the plugin interface without exposing the CLI directly.

**Pull request closed without merging**
