### PR TITLE
doc: correct minor grammar mistakes

### PR DESCRIPTION
**Pull request by rytswd**
### Change Description
- Where: `design.md`
- What: corrected minor grammar mistakes

### Change Motivation
Better readability

---

As this is a minor change, there is no associated issue (as far as I could see).

### CODE REVIEW

**Comment by gabbifish** [comment]
Thank you for your contribution, @rytswd! We really appreciate help with keeping our docs in good shape ✨

**Review by camilamacedo86 — APPROVED** [review]
/approve

**Pull request merged**
