### PR TITLE
:seedling: remove go-apidiff  from kubebuilder CLI deps

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description**
Remove the dep github.com/joelanford/go-apidiff from the required deps for the Kubebuilder CLI/api

**Motivation**
The github.com/joelanford/go-apidiff is only used for a CI check.
It helps us to verify if we are not introducing breaking changes in the project API.
The dep was added for we are able to get it and build it locally to do the test in dev env. (See the makefile target API diff)
So, it should not be added as dep of the project since the project itself does not requires it. 

**Local Test**
Screenshot 2022-04-05 at 01 28 21

Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/2594

### CODE REVIEW

**Comment by camilamacedo86** [comment]
c/c @AlmogBaku

**Comment by AlmogBaku** [comment]
TBH, I'm in favor of removing the tools completely.
Especially since https://github.com/joelanford/go-apidiff/pull/16 is fixing the issue, and we would be able to use that via `go install`

**Comment by camilamacedo86** [comment]
HI @AlmogBaku, 

> TBH, I'm in favor of removing the tools completely.
> Especially since https://github.com/joelanford/go-apidiff/pull/16 is fixing the issue, and we would be able to use that via go install

The PR: https://github.com/joelanford/go-apidiff/pull/16/files changes the dep of goapidiff.
So we would still need to build it locally to have the target right?
If yes, that does not solve the issue over we have as dep for the Kubebuilder CLI/API a module that is **not** used by it at all.

**Comment by AlmogBaku** [comment]
1. No, we won't need to compile it locally.
After https://github.com/joelanford/go-apidiff/pull/16 will be merged and released, we'll be able to just replace the Makefile target to use `go install` and could get rid of the `tools` package

2. The CI doesn't use it anyway. The CI uses a GitHub Action which includes the compiled binary (and not the `tools` package)

**Comment by camilamacedo86** [comment]
Hi @AlmogBaku, 
Regards https://github.com/kubernetes-sigs/kubebuilder/pull/2601#issuecomment-1089101545 
So that is great and make sense. Closing this one in favor of.

**Pull request closed without merging**
