### PR TITLE
use the same alias `kbatchv1` for package k8s.io/api/batch/v1 through…

### PR DESCRIPTION
**Pull request by ziyi-yan**
…out the tutorial project

### CODE REVIEW

**Comment by DirectXMan12** [comment]
/hold

see my comment over on the other PR: https://github.com/kubernetes-sigs/kubebuilder/pull/898#issuecomment-516205726

**Comment by camilamacedo86** [comment]
HI @ziyi-yan, 

If you still thinking that this PR should be merged, could you please rebase it with the master branch? 
Also, if not could you please close this one.

**Comment by DirectXMan12** [comment]
closing for now due to no response

**Pull request closed without merging**
