### PR TITLE
📖 fix: sync docs tutorial with latest kb

### PR DESCRIPTION
**Pull request by Kavinjsir**
### Description

Align the `makefile` scaffolded in component-config-tutorial with the latest Kubebuilder.

### Motivation

Resolve the CI `check testdata` error on master branch.

### CODE REVIEW

**Comment by Kavinjsir** [comment]
@camilamacedo86 Initialize a pr for a quick fix to [the CI error ](https://github.com/kubernetes-sigs/kubebuilder/actions/runs/4107998518/jobs/7091049843#step:7:39)on the master branch.

**Comment by Kavinjsir** [comment]
Also, I'm interested in our PR merge strategy, it looks it allows the merge from a PR that inherits from an older commit history.

**Review by camilamacedo86 — APPROVED** [review]
/pull-kubebuilder-e2e-k8s-1-26-0 

/lgtm

/approved

**Comment by camilamacedo86** [comment]
The error faced `Test started today at 4:53 AM error after 4m12s. ([more info](https://prow.k8s.io/spyglass/lens/metadata/iframe?req=%7B%22artifacts%22%3A%5B%22finished.json%22%2C%22podinfo.json%22%2C%22prowjob.json%22%2C%22started.json%22%5D%2C%22index%22%3A0%2C%22src%22%3A%22gs%2Fkubernetes-jenkins%2Fpr-logs%2Fpull%2Fkubernetes-sigs_kubebuilder%2F3209%2Fpull-kubebuilder-e2e-k8s-1-26-0%2F1623183097849712640%22%7D&topURL=https%3A//prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kubebuilder/3209/pull-kubebuilder-e2e-k8s-1-26-0/1623183097849712640&lensIndex=0#))

Job execution failed: Pod got deleted unexpectedly` does not seems have relation with this changes at all.

I am moving forward with and would be nice also get the test in the infra prow upgraded to use k8s 1.26.1 instead.

**Pull request merged**
