### PR TITLE
⚠️ : upgrade k8s 1.27.1 to 1.28.0 and controller-runtime from 0.15.0 to 0.16.0

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Description

- Upgrade k8s from 1.27.1 to 1.28.0
- Upgrade controller-runtime from 0.15.0 to 0.16.0

⚠️ Controller-runtime has breaking changes see: https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.16.0. Note that the some changes was required to be introduced in the main.go and in the webhook suite test.

   1. Convert Manager Option field `MetricsBindAddress` to `Metrics`.
       (Relative PR: https://github.com/kubernetes-sigs/controller-runtime/pull/2407)
    2. Remove Manager Option fields `Host`, `Port`, `CertDir` since they are deprecated and set by default webhook options.
       (Relative PR: https://github.com/kubernetes-sigs/controller-runtime/pull/2422)

### CODE REVIEW

**Comment by Kavinjsir** [comment]
@camilamacedo86 Looks like we have duplicate works, I just close my https://github.com/kubernetes-sigs/kubebuilder/pull/3569 as per duplicate here.


One issue happens to me is that, when running `make test-testdata`, it would fail in `testdata/project-v4-declarative-v1`, where errors occur when running `go vet`:
```
❯ make vet
go vet ./...
# sigs.k8s.io/kustomize/kyaml/openapi
../../../../go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.9/openapi/openapi.go:656:33: cannot use doc (variable of type *"github.com/google/gnostic/openapiv2".Document) as *"github.com/google/gnostic-models/openapiv2".Document value in argument to swagger.FromGnostic
# k8s.io/kubectl/pkg/util/openapi
../../../../go/pkg/mod/k8s.io/kubectl@v0.26.3/pkg/util/openapi/openapi_getter.go:36:42: cannot use &CachedOpenAPIGetter{} (value of type *CachedOpenAPIGetter) as discovery.OpenAPISchemaInterface value in variable declaration: *CachedOpenAPIGetter does not implement discovery.OpenAPISchemaInterface (wrong type for method OpenAPISchema)
                have OpenAPISchema() (*"github.com/google/gnostic/openapiv2".Document, error)
                want OpenAPISchema() (*"github.com/google/gnostic-models/openapiv2".Document, error)
../../../../go/pkg/mod/k8s.io/kubectl@v0.26.3/pkg/util/openapi/openapi_getter.go:49:28: cannot use g.openAPIClient.OpenAPISchema() (value of type *"github.com/google/gnostic-models/openapiv2".Document) as *"github.com/google/gnostic/openapiv2".Document value in assignment
../../../../go/pkg/mod/k8s.io/kubectl@v0.26.3/pkg/util/openapi/openapi_getter.go:78:46: cannot use oapi (variable of type *"github.com/google/gnostic-models/openapiv2".Document) as *"github.com/google/gnostic/openapiv2".Document value in argument to NewOpenAPIData
../../../../go/pkg/mod/k8s.io/kubectl@v0.26.3/pkg/util/openapi/openapi.go:52:38: cannot use doc (variable of type *"github.com/google/gnostic/openapiv2".Document) as *"github.com/google/gnostic-models/openapiv2".Document value in argument to proto.NewOpenAPIData
make: *** [vet] Error 1
~/pro/kubebuilder/testdata/project-v4-declarative-v1 bump-controller-runtime*
```

I'm looking into why, though quite familiar with the declarative plugin..

**Comment by camilamacedo86** [comment]
/hold

Blocked by bump the project: https://github.com/kubernetes-sigs/kubebuilder-declarative

And then, get the commit within the changes. 

c/c @varshaprasad96 @Kavinjsir

**Review by Kavinjsir — APPROVED** [review]

**Comment by camilamacedo86** [comment]
I will move forward with this one.
When we bump controller-runtime we need to force.

**Pull request merged**
