### PR TITLE
:seeding: rebase v2 into release-2

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description**
Rebase branch v2 into release-2

**Motivation**
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/1948

### CODE REVIEW

**Comment by estroz** [comment]
Holding for signoff

/hold
/lgtm

**Comment by camilamacedo86** [comment]
HI @estroz, @Adirio 

Could we get merged now?

**Review by estroz — APPROVED** [review]
/lgtm

**Pull request merged**
