### PR TITLE
🐛 : Correct specs in testdata for project v4

### PR DESCRIPTION
**Pull request by Kavinjsir**
### Description
Update versions, specs in testdata for project-v4

### Motivation
Some specifications in the current testdata are unaligned with manifests generated by `make generate`.

The updated codes are attempt to in align with what `make generate` provides.

### CODE REVIEW

**Comment by Kavinjsir** [comment]
This is an attempt to fix https://github.com/kubernetes-sigs/kubebuilder/issues/2746

**Review by varshaprasad96 — APPROVED** [review]
/lgtm

**Comment by varshaprasad96** [comment]
/hold
Holding for other reviews and confirmation.
@camilamacedo86 @rashmigottipati

**Comment by camilamacedo86** [comment]
@Kavinjsir @varshaprasad96 
I think is better we revert: https://github.com/kubernetes-sigs/kubebuilder/pull/2748
Indeed do it after the release.

**Comment by camilamacedo86** [comment]
Closing this one since we revert the PR

**Pull request closed without merging**
