### PR TITLE
📖 : (README) Fix slack channel access address

### PR DESCRIPTION
**Pull request by uos-ljtian**
Repair access address.

https://slack.k8s.io/#kubebuilder -> https://kubernetes.slack.com/messages/#kubebuilder

### CODE REVIEW

**Comment by uos-ljtian** [comment]
@camilamacedo86 Please review

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Comment by camilamacedo86** [comment]
This one change only README
the issue with the CI was fixed in: https://github.com/kubernetes-sigs/kubebuilder/pull/3824
we can safely move forward

**Pull request merged**
