### PR TITLE
🏃 Bump k8s tools to 1.16.4

### PR DESCRIPTION
**Pull request by vincepri**
Changes:

Use Kubernetes 1.16.4 binaries in tests
Use Kubernetes 1.16.4 in release bundle

### CODE REVIEW

**Comment by camilamacedo86** [comment]
Hi @vincepri,

Shows that the bin `gcr.io/kubebuilder/thirdparty-linux:1.16.4` do not exist and because of this the PR is failing in the tests. Also, the version of k8s should not be updated in the [travis](https://github.com/kubernetes-sigs/kubebuilder/blob/master/.travis.yml#L17) and in the `pull-kubebuilder-e2e-k8s-1-16-2`?

**Comment by vincepri** [comment]
@camilamacedo86 I updated the tests to use v1.16.2, but it seems they're still failing for the same reason. I'm assuming there is some manual step needed to release controller-tools?

**Comment by camilamacedo86** [comment]
Hi @vincepri, 

The error faced is because the `gcr.io/kubebuilder/thirdparty-darwin:1.16.2` used to replace `gcr.io/kubebuilder/thirdparty-darwin:1.15.5` do not exist. See: https://console.cloud.google.com/gcr/images/kubebuilder/GLOBAL/thirdparty-linux?tag=1.16.4&gcrImageListsize=30. 

What is your goal with this PR? Is just update the k8s version?

**Comment by vincepri** [comment]
I would like to make `kubebuilder-tools` with Kubernetes >=1.16.x available, so we can start using CRD v1 across Cluster API projects.

It seems this might need some manual attention / build?

**Comment by mengqiy** [comment]
IIRC we have to push a git tag to `tools-release` branch to trigger a build.
Will do this tomorrow

**Comment by vincepri** [comment]
Thanks @mengqiy

**Comment by mengqiy** [comment]
@vincepri I tried to change to base branch. But it turned out github closed it for some reason :(

**Comment by vincepri** [comment]
I can push another PR to the other branch if you prefer

**Comment by mengqiy** [comment]
We need to first build the tools: I created #1283
Then switch to use them in another PR like https://github.com/kubernetes-sigs/kubebuilder/pull/1123/files

**Comment by vincepri** [comment]
@mengqiy Do you want to reopen this one and reset the branch to master?

**Comment by mengqiy** [comment]
@vincepri Yes please

**Comment by vincepri** [comment]
Mind changing the base branch first? I don't have permissions for this repo

**Comment by mengqiy** [comment]
It seems this PR currently is in a weird state which can neither be re-open nor change base branch.
@vincepri  Can you please create a new PR?

**Pull request closed without merging**
