### PR TITLE
:sparkles: (Kustomize/v2, go/v4): upgrade controller-tools from 0.12.0 to 0.13.0

### LINKED ISSUE #3549: Bump K8s dependencies to 1.28
### What do you want to happen?

Creating this issue to track the bumping of K8s dependencies to 1.28.

Controller-runtime (https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.16.0) and controller-tools (https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.13.0) have released a version with 1.28 releases of k8s dependencies. 

Things to do:
- [ ] Bump deps in Kubebuilder binary 
- [ ] Bump reps in all the plugins 
- [ ] Bump deps in KB declarative pattern (the PR to deprecate and remove it is still in progress)

Refer to https://github.com/kubernetes-sigs/kubebuilder/pull/3444 to know how it was done for k8s 1.27 bumps.

### Extra Labels

_No response_

### PR DESCRIPTION
**Pull request by Kavinjsir**
### Description

Bump controller-tools to v0.13.0

### Motivation

Partially resolve #3549 to support Kubernetes v1.28.0

### CODE REVIEW

**Review by camilamacedo86 — COMMENTED** [review]
Hi @Kavinjsir 

Yep that is great.
Thank you for the collaboration 🥇 

Just few nits:
- missing run make generate
- the title of the PR needs to use the emoj `:sparkles:` so that it will be used to generate teh release notes. Also, would be good we do something like "`:sparkles: (Kustomize/v2, go/v4): upgrade controller-tools from 0.12.0 to 0.13.0`" (this one I updated. I hope that you do not mind)

**Review by camilamacedo86 — APPROVED** [review]
Great 

/approved

**Comment by camilamacedo86** [comment]
@Kavinjsir please see that we need to fix the commit message 
It is making the CI falling
Screenshot 2023-08-26 at 06 11 18

**Comment by Kavinjsir** [comment]
Hey @camilamacedo86 , sorry I just saw your reviews. Thx for helping me with fixing a number errors in the PR!!

For now, it looks two issues I'm not quite sure:
1. `make apidiff` would fail due to the unmatched controller-tools version from the master branch.
2. It seems like the CI stage `Test verification` failed due to some changes in the docs directory. I'm looking on that now, the interesting thing is: either `make generate` or `make generate-docs` or `make check-docs` worked fine from my local...

**Comment by camilamacedo86** [comment]
HI @Kavinjsir, 

> make apidiff would fail due to the unmatched controller-tools version from the master branch.
That is expected. We need to force when we do those bumps. 

> It seems like the CI stage Test verification failed due to some changes in the docs directory. I'm looking on that now, the interesting thing is: either make generate or make generate-docs or make check-docs worked fine from my local...

It seems that in the script to generate the docs it is missing we call `go mod tidy`
See the error

```
TODO: update tutorial
  running: go get github.com/robfig/cron
  running: make build
  running: go get github.com/robfig/cron
  running: make build
 M docs/book/src/cronjob-tutorial/testdata/project/go.sum
diff --git a/docs/book/src/cronjob-tutorial/testdata/project/go.sum b/docs/book/src/cronjob-tutorial/testdata/project/go.sum
index 2f447cd..da86b48 100644
--- a/docs/book/src/cronjob-tutorial/testdata/project/go.sum
make: *** [Makefile:80: check-docs] Error 1
+++ b/docs/book/src/cronjob-tutorial/testdata/project/go.sum
```

**Review by camilamacedo86 — APPROVED** [review]

**Pull request merged**
