### PR TITLE
🌱  Build kubebuilder-tools for Kubernetes 1.22.1 and runtime 0.10.0

### PR DESCRIPTION
**Pull request by hickeyma**
Signed-off-by: Martin Hickey <martin.hickey@ie.ibm.com>

~~This update of Kubernetes and controller-runtime helps fix envtest issues as raised in https://github.com/kubernetes-sigs/controller-runtime/issues/1571.~~ Thanks to @camilamacedo86 for helping me with this and @joelanford for his solution in https://github.com/operator-framework/helm-operator-plugins/pull/102.

### CODE REVIEW

**Comment by estroz** [comment]
Only 1.22.0 tools exist (see #2287), so you'd have to specify that version in docs. Feel free to submit a tools-releases branch PR if you'd like to see 1.22.1 available though!

**Comment by hickeyma** [comment]
Tested using the [cronjob-tutorial](https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs/book/src/cronjob-tutorial/testdata/project), results as follows:

- Kubernetes v1.20.2: No issue
- Kubernetes v1.21.4: Issue as stated in https://github.com/kubernetes-sigs/controller-runtime/issues/1571 
- Kubernetes v1.22.0: Issue as stated in https://github.com/kubernetes-sigs/controller-runtime/issues/1571  

So, looks like issue in Kubernetes v1.21, v1.22.

**Comment by hickeyma** [comment]
@estroz I wonder should we close this PR considering it doesn't fix the envTest issue.

**Pull request closed without merging**
