### PR TITLE
:seedling: update module v2/ to v3/

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description**

Bump v3/ module to prepare the master for the next release (3.0.0)

**Motivation**
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/1798

### CODE REVIEW

**Comment by Adirio** [comment]
@camilamacedo86 I think this should be the last thing to get merged before the v3 release, and trust me, rebasing this PR is going to be a pain. It is better to wait until the end and do a search and replace that try to keep this PR up to date. I suffered it with the v2 equivalent.

**Comment by camilamacedo86** [comment]
Hi @Adirio, 

over: https://github.com/kubernetes-sigs/kubebuilder/pull/1825 IMO we should merge this one and we should not actually bump v2/ at all. See that: 

Could we really do a patch release from master? 
- we remove the v1 from master
- we changed the project file and introduced the plugin layout 

In this way, if we do a release now. Will the CLI work with the same projects that it was able to work before the changes made?

**Comment by camilamacedo86** [comment]
Close this one because besides we are unable to push a patch release from master the import of the pkg will still v2.3.1-abc-123.

**Pull request closed without merging**
