### PR TITLE
📖 : delete cronjob tutorial Incorrect kustomization.yaml

### PR DESCRIPTION
**Pull request by xiao-jay**
#3249 
Delete cronjob tutorial Incorrect code in kustomization.yaml, that will lead to `make deploy` error

### CODE REVIEW

**Review by camilamacedo86 — DISMISSED** [review]
The right approach would be update the project.
It seems outdated. 

However, that is fine we can move forward with this only change.
Also, see that I am changing the title. The right emoji for this one is 📖

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Review by everettraven — APPROVED** [review]
Looks reasonable to me.

/lgtm

**Comment by everettraven** [comment]
These APIDiff check failures seem weird. I'm not sure why changing the docs would cause a failure in the diff

**Comment by everettraven** [comment]
> These APIDiff check failures seem weird. I'm not sure why changing the docs would cause a failure in the diff

Actually just noticed these are all related to the kustomize/v2 plugin. This PR was created before the kustomize/v2 plugin was stabilized so it is in a weird state where running against the PR it is still kustomize/v2-alpha vs the main branch being kustomize/v2.

I think to fix this the PR just needs to be closed and then reopened

**Comment by camilamacedo86** [comment]
Hi @everettraven,

https://github.com/kubernetes-sigs/kubebuilder/pull/3256#issuecomment-1458266775
It seems a bug with the go-apidiff.  I will force this one and we keep the eyes on it. Therefore, if we see more issues we need to further investigate.

**Pull request merged**
