### PR TITLE
✨ Build kubebuilder-tools for k8s 1.28.0

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

**Comment by sbueringer** [comment]
@killianmuldoon hold for? (you don't have approver rights in this repo anyway :))

**Comment by killianmuldoon** [comment]
No need to hold - just didn't know what the approval flow is in this repo - and auto-wrote `/approve`  :sweat_smile:

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Comment by varshaprasad96** [comment]
@sbueringer @furkatgofurov7 is there a tight timeline you are looking at to get envtest binaries for 1.28? The build is usually triggered along with a KB release. Now that we have c-r and controller-tools updated, we should be able to get [this](https://github.com/kubernetes-sigs/kubebuilder/issues/3549) in soon.

**Comment by killianmuldoon** [comment]
/hold cancel

(just undoing my previous hold)

**Comment by sbueringer** [comment]
> @sbueringer @furkatgofurov7 is there a tight timeline you are looking at to get envtest binaries for 1.28? The build is usually triggered along with a KB release. Now that we have c-r and controller-tools updated, we should be able to get [this](https://github.com/kubernetes-sigs/kubebuilder/issues/3549) in soon.

From my side there is no rush.

**Comment by furkatgofurov7** [comment]
> @sbueringer @furkatgofurov7 is there a tight timeline you are looking at to get envtest binaries for 1.28? The build is usually triggered along with a KB release. Now that we have c-r and controller-tools updated, we should be able to get [this](https://github.com/kubernetes-sigs/kubebuilder/issues/3549) in soon.

>From my side there is no rush.

Same, just wanted to see if we can get more eyes on this, thanks for info @varshaprasad96

**Review by camilamacedo86 — APPROVED** [review]
/lgtm
/aproved

**Comment by camilamacedo86** [comment]
/hold cancel

Yes, we can move forward within.
However, could you please also do a follow up PR to bump ETCD (See; https://github.com/kubernetes-sigs/kubebuilder/blob/tools-releases/build/thirdparty/linux/Dockerfile)

**Pull request merged**
