### PR TITLE
:sparkles: *: upgrade kube-rbac-proxy to v0.8.0

### LINKED ISSUE #1785: Update kube-rbac-proxy to v0.8.0 release
Per brancz/kube-rbac-proxy#99 (comment) has been pushed to quay.io/brancz/kube-rbac-proxy:v0.8.0. What is the process to update the gcr.io/kubebuilder/kube-rbac-proxy? Is this hand tagged and pushed by a maintainer?

Could you push it or retag it ? Thanks.

/kind bug

### PR DESCRIPTION
**Pull request by estroz**
This PR upgrades kube-rbac-proxy image version from v0.5.0 to v0.8.0, which has a rootless feature and no breaking changes (afaik).

Closes #1785

### CODE REVIEW

**Comment by estroz** [comment]
Looks like there's some issue with k8s v1.15.3 resulting in kube-rbac-proxy:v0.8.0 [not being pullable](failed to unpack image on snapshotter overlayfs: content digest sha256:5a9f8e2f60fc4d02e364fa0192c01c79e8fac7e0c6a01cbc5b17152d6f21deae: not found). I think I've reproduced this locally; v1.15.13 works fine. Will update the prow config then rerun these tests.

**Comment by estroz** [comment]
Blocked on https://github.com/kubernetes/test-infra/pull/20530

**Review by camilamacedo86 — APPROVED** [review]
terrific 🥇 

/lgtm

**Pull request merged**
