### PR TITLE
Bump up the version of kind to 0.7.0

### LINKED ISSUE #1308: Update to use the latest kind v0.7.0+
kubebuilder currently uses v0.6.0, we should update to use v0.7.0+

### PR DESCRIPTION
**Pull request by bharaththiruveedula**
Signed-off-by: Bharath Thiruveedula <bharath_ves@hotmail.com>

Closes #1308

### CODE REVIEW

**Comment by Adirio** [comment]
@bharaththiruveedula You want to edit the description of the PR and add `Closes #1308` so that the related issue gets closed by the robot when this PR gets merged.

**Comment by Adirio** [comment]
@bharaththiruveedula The commit message can't have that, it needs to be the PR description here in GitHub. Edit the top message that currently has your signature by pressing the triple dot at the top right side, and then edit message.

**Comment by bharaththiruveedula** [comment]
> @bharaththiruveedula The commit message can't have that, it needs to be the PR description here in GitHub. Edit the top message that currently has your signature by pressing the triple dot at the top right side, and then edit message.

Got it . Just updated

**Comment by joelanford** [comment]
It looks like `kind v0.7.0` uses kubernetes 1.17. Are there any timing considerations for bumping and releasing controller-runtime and controller-tools to kubernetes 1.17 dependencies?

See https://github.com/kubernetes-sigs/controller-runtime/pull/754

controller-tools has 1.17 deps on `master`, but may need a release.

/cc @DirectXMan12

**Comment by Adirio** [comment]
> It looks like `kind v0.7.0` uses kubernetes 1.17.

IIRC we are setting the k8s version with environmental variables for Travis.

**Pull request merged**
