### PR TITLE
🌱 fix file.Template to machinery.Template in the comments

### PR DESCRIPTION
**Pull request by monteiro-renato**

### CODE REVIEW

**Review by camilamacedo86 — APPROVED** [review]
/lgtm
/approve
/ok-to-test

**Comment by monteiro-renato** [comment]
Updated the commit message now.

**Comment by camilamacedo86** [comment]
/lgtm

👍 Thank you

**Comment by monteiro-renato** [comment]
Hmm, running `make generate` locally did indeed update those files; however, I don't think these updates should be triggered by my changes?

**Comment by monteiro-renato** [comment]
I see it's broken in main as well.
I've opened a PR just to run `make generate`.
https://github.com/kubernetes-sigs/kubebuilder/pull/4353

**Comment by monteiro-renato** [comment]
Rebased, it should pass CI now.

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Pull request merged**
