### PR TITLE
plugins: update from master

### PR DESCRIPTION
**Pull request by estroz**

### CODE REVIEW

**Comment by Adirio** [comment]
Yes, I know its a rebase. That's the reason I said that providing a list of merge conflicts would be useful as the diff provided by GitHub in this cases is useless (too many source files and lines of code to review). Providing a list of merge conflicts and how they were resolved would make revieweing this kind of rebases very easy instead (he is rebasing code he did not merge, so by resolving a conflict he may introduce a subtle bug and thats what we should review).

**Comment by camilamacedo86** [comment]
HI @Adirio, 

You can check the commits and the `Merge branch 'master' into rebase-plugins` is that one where the conflicts were addressed.

**Comment by estroz** [comment]
/hold

Will add conflict resolutions.

**Pull request closed without merging**
