### PR TITLE
upgrade controller-runtime from v0.5.0 to v0.6.0 and k8s api from v0.17.2 to v0.18.2

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description**
- upgrade controller-runtime from v0.5.0 to v0.6.0
- k8s api from v0.17.2 to v0.18.2

NOTES: Has breaking changes. See: https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.6.0

### CODE REVIEW

**Comment by camilamacedo86** [comment]
/hold

@mengqiy I think we need to move within v3.0.0 as well. WDYT?

**Comment by camilamacedo86** [comment]
/hold 

wip: required to check why is not passing in the CI

**Comment by mengqiy** [comment]
Please don't check in vendor folder for v1 generated project.

**Comment by camilamacedo86** [comment]
Hi @mengqiy, 

When we merge the https://github.com/kubernetes-sigs/kubebuilder/pull/1355 I think it will be solved. Because of this I added the hold.

**Comment by camilamacedo86** [comment]
We will not able to move forward here until fix the issue faced with the addon. 
I am closing this one and raise an issue for we are able to work with

**Pull request closed without merging**
