### PR TITLE
Update OWNERS_ALIASES

### PR DESCRIPTION
**Pull request by gerred**
Active on controller runtime, want to make sure I'm active here too. Going for the bold move of maintainer - happy to change this to reviewer.

### CODE REVIEW

**Comment by Adirio** [comment]
Travis fail is due to a bug introduced by #1016 that is fixed in #1288.

**Comment by gerred** [comment]
Thanks @Adirio - stuck between a rock and a hard place. I'll review #1288 in the meantime.

**Comment by gerred** [comment]
Thanks @camilamacedo86 :+1: - I will adjust.

**Comment by DirectXMan12** [comment]
needs rebase to merge properly otherwise fine I think

**Comment by DirectXMan12** [comment]
@gerred I'd also prefer to see a few more reviews here first, if you can
/hold

**Comment by gerred** [comment]
@DirectXMan12 Absolutely :+1:. What wasn't clear when I opened this was if we were grouping these all across the entire subproject rather than on a per-repo basis, and based on what we talked about, it makes much more sense about having a consistent set of reviewers/approvers per project. I think there's enough to do over in CR that I'll focus there for now, and if my help can be useful over on this side and in CT, I can always open this PR again.

I'll close for now. :)

**Pull request closed without merging**
