### PR TITLE
:book: Fix typo in api-changes.md

### PR DESCRIPTION
**Pull request by shubhamrajvanshi**
:book: Fix a typo in the docs

### CODE REVIEW

**Review by rashmigottipati — APPROVED** [review]
/ok-to-test

**Review by rashmigottipati — COMMENTED** [review]
/ok-to-test

**Review by rashmigottipati — APPROVED** [review]
/approve

**Review by rashmigottipati — APPROVED** [review]
/lgtm

**Review by camilamacedo86 — APPROVED** [review]

**Pull request merged**
