### PR TITLE
:running: Design for CRD version conversion

### PR DESCRIPTION
**Pull request by droot**
This is a markdown format of https://docs.google.com/document/d/1AbXhGhQduyM1xextudw_hXZKfAACRqEOvBxh61pFMaU/edit?usp=sharing

One component of this design *conversion handler* is being developed in this PR --> https://github.com/kubernetes-sigs/controller-runtime/pull/351

### CODE REVIEW

**Comment by mengqiy** [comment]
Has this PR sync'd with the latest version of https://docs.google.com/document/d/1AbXhGhQduyM1xextudw_hXZKfAACRqEOvBxh61pFMaU/edit?usp=sharing? IIRC you have updated the doc a while ago.

**Comment by DirectXMan12** [comment]
Can you also just make sure to have a discrete example section with a full simple example workflow?  Otherwise good, as long as its up-to-date.

**Comment by DirectXMan12** [comment]
@droot can you make sure this is up-to-date and we'll get it merged for historical reference?

**Comment by DirectXMan12** [comment]
o_O did we never merge this?  let's do so

**Pull request merged**
