### PR TITLE
:sparkles: Cleanup scaffolding 

### LINKED ISSUE #1119: Missing import in scaffolded code
# Bug description
Missing `"k8s.io/apimachinery/pkg/runtime"` import in controller scaffolding.
I think my IDE added the import automatically as I can't find it in the scaffold file.

https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/scaffold/v2/controller.go#L71-L86

/kind bug

### PR DESCRIPTION
**Pull request by Adirio**
Fixes #1119

### CODE REVIEW

**Comment by Adirio** [comment]
@camilamacedo86 

/kind cleanup

**Comment by mengqiy** [comment]
tests are failing, since you will need to run `./generate_golden.sh`

**Comment by mengqiy** [comment]
And don't forget to squash commits before merging.

**Comment by Adirio** [comment]
> tests are failing, since you will need to run `./generate_golden.sh`

I have been unable to do it on Windows 😭 It has issues trying to find if the current directory is in the GOPATH as Linux paths are expected (https://github.com/kubernetes-sigs/kubebuilder/blob/master/common.sh#L44-L54)

**Comment by mengqiy** [comment]
If you check the logs of the failing test, you can find the golden test is failing.
```
diff --git a/testdata/project-v2/controllers/namespace_controller.go b/testdata/project-v2/controllers/namespace_controller.go
index d04e73f..7afaca4 100644
--- a/testdata/project-v2/controllers/namespace_controller.go
+++ b/testdata/project-v2/controllers/namespace_controller.go
@@ -20,11 +20,11 @@ import (
 	"context"
 
 	"github.com/go-logr/logr"
+	"k8s.io/apimachinery/pkg/runtime"
 	ctrl "sigs.k8s.io/controller-runtime"
 	"sigs.k8s.io/controller-runtime/pkg/client"
 
 	corev1 "k8s.io/api/core/v1"
-	"k8s.io/apimachinery/pkg/runtime"
 )
 
 // NamespaceReconciler reconciles a Namespace object
```
Given it's hard to run the script on windows machine. You can simply apply the diff to make the golden test pass.

**Comment by camilamacedo86** [comment]
Hi @Adirio, 
The PR https://github.com/kubernetes-sigs/kubebuilder/pull/1130 was made in order to solve it and help you since you are facing issues to use the golden script.

**Comment by Adirio** [comment]
@camilamacedo86 I should have been more especific on my previous comment. Should have said it was a note to take it into account in case your PR was merged before I could solve the golder test issues. Sorry about that.

**Comment by Adirio** [comment]
Golden test will still fail with this version, will try to solve the issue as @mengqiy suggested or wait for #1130 to be merged.

**Comment by Adirio** [comment]
Okey, every test passed, squashing commits and should be fine to go

@mengqiy @Liujingfang1 @camilamacedo86

**Comment by Adirio** [comment]
/retest

This worked before squashing

**Comment by Adirio** [comment]
Rebased after #1130

**Comment by Adirio** [comment]
@mengqiy @Liujingfang1 @camilamacedo86
All tests passed. #1119 was fixed by #1130 that has already been merged but this PR tackles spaces used for indentation, import order, extra blank lines and an extra import that is not being used. Anything else needed for lgtm and approved labels?

**Pull request merged**
