### PR TITLE
Add Makefile rule to uninstall CRDs

### LINKED ISSUE #1032: Add uninstall Makefile rule
Some people may want to uninstall a CRD after trying out an idea.

Is this just `kustomize build config/crd | kubectl delete -f`.
Or is this too dangerous to make easy?

### PR DESCRIPTION
**Pull request by rudoi**
This PR adds `make uninstall`, which deletes generated CRDs from a cluster. Also adds a section to the quickstart. 

Fixes #1032

### CODE REVIEW

**Comment by mengqiy** [comment]
@rudoi Please rebase and run `./generated_golden.sh`.

**Comment by mengqiy** [comment]
Please rebase first and then retry.

**Comment by camilamacedo86** [comment]
Hi @rudoi, 

The error `missing dot in first path element` faced by you is because you have some issue in your GO env vars setup. Also, note that for you are able to run update the testdata you need be using the go 1.12 and not 1.13.

Run make generate-setup and then generate-testdata to do it by using the Makefile targets.

**Comment by rudoi** [comment]
> Hi @rudoi,
> 
> The error `missing dot in first path element` faced by you is because you have some issue in your GO env vars setup. Also, note that for you are able to run update the testdata you need be using the go 1.12 and not 1.13.
> 
> Run make generate-setup and then generate-testdata to do it by using the Makefile targets.

Thanks @camilamacedo86! Sorry for the delay, was out on vacation.

So I did this, and updated, and pushed up and then this instantly merged? Was that supposed to happen?

**Pull request merged**
